import {
    extractLotFromCrn,
    extractQuarterFromCrn,
    generateBuildingCrns,
    generateDeftCrn,
    parseDeftCrn,
    validateDeftCrn,
} from '@/lib/trust/deft';

describe('generateDeftCrn', () => {
    it('produces correct format', () => {
        const crn = generateDeftCrn(18, '2026-Q1', '452301');
        expect(crn).toMatch(/^452301-0018-2026Q1-\d$/);
    });

    it('is deterministic', () => {
        const crn1 = generateDeftCrn(18, '2026-Q1', '452301');
        const crn2 = generateDeftCrn(18, '2026-Q1', '452301');
        expect(crn1).toBe(crn2);
    });

    it('CRNs for different buildings are different', () => {
        const crnA = generateDeftCrn(1, '2026-Q1', 'TEST-A-001');
        const crnB = generateDeftCrn(1, '2026-Q1', 'TEST-B-001');
        expect(crnA).not.toBe(crnB);
    });

    it('East Gate and Riverside CRNs are different for same lot', () => {
        const crnEG = generateDeftCrn(1, '2026-Q1', 'MOCK-EG-452301');
        const crnRA = generateDeftCrn(1, '2026-Q1', 'MOCK-RA-789101');
        expect(crnEG).not.toBe(crnRA);
    });
});

describe('validateDeftCrn', () => {
    it('accepts CRN generated by generateDeftCrn', () => {
        const crn = generateDeftCrn(18, '2026-Q1', '452301');
        expect(validateDeftCrn(crn)).toBe(true);
    });

    it('rejects CRN with wrong check digit', () => {
        const crn = generateDeftCrn(18, '2026-Q1', '452301');
        // Flip the last digit
        const lastDash = crn.lastIndexOf('-');
        const digit = parseInt(crn.slice(lastDash + 1));
        const wrongDigit = (digit + 1) % 10;
        const invalidCrn = crn.slice(0, lastDash + 1) + wrongDigit;
        expect(validateDeftCrn(invalidCrn)).toBe(false);
    });
});

describe('parseDeftCrn', () => {
    it('correctly extracts all components', () => {
        const crn = generateDeftCrn(18, '2026-Q1', '452301');
        const parsed = parseDeftCrn(crn);
        expect(parsed).not.toBeNull();
        expect(parsed?.billerCode).toBe('452301');
        expect(parsed?.lotNumber).toBe(18);
        expect(parsed?.quarter).toBe('2026-Q1');
    });

    it('returns null for empty string', () => {
        expect(parseDeftCrn('')).toBeNull();
    });
});

describe('extractLotFromCrn', () => {
    it('returns correct lot number', () => {
        const crn = generateDeftCrn(42, '2026-Q1', '452301');
        expect(extractLotFromCrn(crn)).toBe(42);
    });
});

describe('extractQuarterFromCrn', () => {
    it('returns correct quarter', () => {
        const crn = generateDeftCrn(1, '2026-Q2', '452301');
        expect(extractQuarterFromCrn(crn)).toBe('2026-Q2');
    });
});

describe('generateBuildingCrns', () => {
    it('returns correct count of CRNs', () => {
        const units = Array.from({length: 87}, (_, i) => ({lot_number: i + 1}));
        const map = generateBuildingCrns(units, '2026-Q1', 'MOCK-EG-452301');
        expect(map.size).toBe(87);
    });

    it('all CRNs are unique within a building', () => {
        const units = Array.from({length: 87}, (_, i) => ({lot_number: i + 1}));
        const map = generateBuildingCrns(units, '2026-Q1', 'MOCK-EG-452301');
        const crns = Array.from(map.values());
        const unique = new Set(crns);
        expect(unique.size).toBe(87);
    });

    it('all CRNs pass validateDeftCrn', () => {
        const units = Array.from({length: 10}, (_, i) => ({lot_number: i + 1}));
        const map = generateBuildingCrns(units, '2026-Q1', 'TEST-A-001');
        for (const crn of map.values()) {
            expect(validateDeftCrn(crn)).toBe(true);
        }
    });
});
