"""
migration_010_backfill_building_id_from_plan_id.py

Scans every tenant-scoped collection in the database for documents that have
a ``plan_id`` field but are missing ``building_id`` (null or absent), and
backfills ``building_id = plan_id`` for each such document.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
AUDIT CLASSIFICATION TABLE
(generated by manual code review on 2026-04-23)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Legend:
  COMPAT_SHIM  — Already handles both plan_id and building_id.  No fix needed.
  ALIAS_READ   — Reads plan_id as fallback to building_id.  Safe pattern.
  ACTIVE_WRITE — Writes plan_id WITHOUT also writing building_id.  BUG — needs fix.
  DEAD_READ    — References plan_id in a way whose result is never meaningfully used.
                 Flag for eventual removal.

┌──────────────────────────────────────────────────────────────────────────────────────────────────┬─────────────────┬─────────────────────────────────────────────────────────────────────────┐
│ File                                                  │ Classification  │ Notes                                                                   │
├──────────────────────────────────────────────────────────────────────────────────────────────────┼─────────────────┼─────────────────────────────────────────────────────────────────────────┤
│ backend/database.py                                   │ COMPAT_SHIM     │ The DB layer itself. Injects {"$or":[{building_id},{plan_id}]} on reads. │
│                                                       │                 │ On insert/replace, accepts either field. This IS the shim — canonical.  │
├──────────────────────────────────────────────────────────────────────────────────────────────────┼─────────────────┼─────────────────────────────────────────────────────────────────────────┤
│ backend/models/finance.py                             │ COMPAT_SHIM     │ Pydantic AliasChoices("building_id","plan_id") on all finance models.    │
│                                                       │                 │ Also sets plan_id as a mirror field for wire compatibility. No writes.   │
├──────────────────────────────────────────────────────────────────────────────────────────────────┼─────────────────┼─────────────────────────────────────────────────────────────────────────┤
│ backend/models/financial_models.py                    │ COMPAT_SHIM     │ Same AliasChoices pattern. Pure schema definitions, no DB writes.        │
├──────────────────────────────────────────────────────────────────────────────────────────────────┼─────────────────┼─────────────────────────────────────────────────────────────────────────┤
│ backend/repositories/financial_repository.py          │ COMPAT_SHIM     │ Explicitly pops plan_id on reads for backward compat (lines 109, 158,   │
│                                                       │                 │ 303). Never writes plan_id. Clean pattern.                               │
├──────────────────────────────────────────────────────────────────────────────────────────────────┼─────────────────┼─────────────────────────────────────────────────────────────────────────┤
│ backend/routers/auth.py                               │ DEAD_READ       │ Line 482: plan_id mentioned only in a comment about bypassing the $or    │
│                                                       │                 │ injection. No functional plan_id read/write. Safe to ignore.             │
├──────────────────────────────────────────────────────────────────────────────────────────────────┼─────────────────┼─────────────────────────────────────────────────────────────────────────┤
│ backend/routers/payment_plans.py                      │ DEAD_READ       │ plan_id is a URL path parameter (payment plan document ID, NOT the       │
│                                                       │                 │ building identifier). Variable name collision — not the legacy field.    │
├──────────────────────────────────────────────────────────────────────────────────────────────────┼─────────────────┼─────────────────────────────────────────────────────────────────────────┤
│ backend/routers/levy_scenarios.py                     │ ALIAS_READ      │ Line 70: reads user.get("building_id") or user.get("plan_id"). Safe      │
│                                                       │                 │ fallback read, no writes.                                                │
├──────────────────────────────────────────────────────────────────────────────────────────────────┼─────────────────┼─────────────────────────────────────────────────────────────────────────┤
│ backend/routers/reconciliation.py                     │ ACTIVE_WRITE    │ Lines 308, 331: levy_categories and annual_levies inserts write          │
│                                                       │                 │ plan_id=building_id WITHOUT building_id alongside it in the $set dict.   │
│                                                       │                 │ building_id IS present in the query filter but NOT in the $set payload.  │
│                                                       │                 │ Documents created by upsert may lack building_id in the document body.   │
├──────────────────────────────────────────────────────────────────────────────────────────────────┼─────────────────┼─────────────────────────────────────────────────────────────────────────┤
│ backend/routers/strata_sync.py                        │ COMPAT_SHIM     │ Lines 308, 331: $set includes BOTH building_id and plan_id. Correct.     │
├──────────────────────────────────────────────────────────────────────────────────────────────────┼─────────────────┼─────────────────────────────────────────────────────────────────────────┤
│ backend/routers/finance.py                            │ COMPAT_SHIM     │ Lines 3820, 3878, 3963: all three insert_one/update_one calls include    │
│                                                       │                 │ BOTH building_id and plan_id in the document body. Correct pattern.      │
├──────────────────────────────────────────────────────────────────────────────────────────────────┼─────────────────┼─────────────────────────────────────────────────────────────────────────┤
│ backend/routers/finance_intelligence.py               │ COMPAT_SHIM     │ Lines 726-729, 773: sets plan_id only if missing; building_id is set     │
│                                                       │                 │ unconditionally. Both fields always end up present.                      │
├──────────────────────────────────────────────────────────────────────────────────────────────────┼─────────────────┼─────────────────────────────────────────────────────────────────────────┤
│ backend/cron/cron_levy_reminders.py                   │ ALIAS_READ      │ Lines 32-34: reads {"plan_id":1,"building_id":1}, returns               │
│                                                       │                 │ b.get("plan_id") or b.get("building_id"). Pure read fallback.            │
├──────────────────────────────────────────────────────────────────────────────────────────────────┼─────────────────┼─────────────────────────────────────────────────────────────────────────┤
│ backend/cron/cron_maintenance_intelligence.py         │ ALIAS_READ      │ Lines 79-85: same pattern — projects both fields, uses first non-null.   │
├──────────────────────────────────────────────────────────────────────────────────────────────────┼─────────────────┼─────────────────────────────────────────────────────────────────────────┤
│ backend/cron/cron_notification_digest.py              │ ALIAS_READ      │ Lines 33-38: same pattern.                                               │
├──────────────────────────────────────────────────────────────────────────────────────────────────┼─────────────────┼─────────────────────────────────────────────────────────────────────────┤
│ backend/cron/cron_nsw_compliance.py                   │ COMPAT_SHIM     │ Line 44: query uses {"$or":[{"plan_id":bid},{"building_id":bid}]}         │
│                                                       │                 │ mirroring the DB layer. Line 64: alias read fallback. No writes.         │
├──────────────────────────────────────────────────────────────────────────────────────────────────┼─────────────────┼─────────────────────────────────────────────────────────────────────────┤
│ backend/cron/cron_pm_scheduler.py                     │ ALIAS_READ      │ Lines 91-96: projects both, uses first non-null. No writes.              │
├──────────────────────────────────────────────────────────────────────────────────────────────────┼─────────────────┼─────────────────────────────────────────────────────────────────────────┤
│ backend/cron/cron_ppm_notifications.py                │ ALIAS_READ      │ Lines 339-344: same projection + fallback pattern. No writes.            │
├──────────────────────────────────────────────────────────────────────────────────────────────────┼─────────────────┼─────────────────────────────────────────────────────────────────────────┤
│ backend/cron/cron_suburb_radar.py                     │ ALIAS_READ      │ Lines 117-122: same projection + fallback pattern. No writes.            │
├──────────────────────────────────────────────────────────────────────────────────────────────────┼─────────────────┼─────────────────────────────────────────────────────────────────────────┤
│ backend/seeds/enhanced_dashboard.py                   │ ACTIVE_WRITE    │ Lines 82, 91, 134, 150: writes plan_id="13195" to annual_levies and      │
│                                                       │                 │ unit_levy_ledger WITHOUT also writing building_id. These seeded records  │
│                                                       │                 │ will only be matched by the $or shim in database.py, never by a direct  │
│                                                       │                 │ building_id filter. This is a pre-existing data quality issue that       │
│                                                       │                 │ migration_010 will fix in the DB.                                        │
├──────────────────────────────────────────────────────────────────────────────────────────────────┼─────────────────┼─────────────────────────────────────────────────────────────────────────┤
│ backend/seeds/finance_history.py                      │ COMPAT_SHIM     │ Lines 90, 139: PLAN_ID variable used for both plan_id and building_id    │
│                                                       │                 │ fields (line 91: "building_id": PLAN_ID, line 90: "plan_id": PLAN_ID).   │
│                                                       │                 │ Both fields always written together. Correct.                            │
├──────────────────────────────────────────────────────────────────────────────────────────────────┼─────────────────┼─────────────────────────────────────────────────────────────────────────┤
│ backend/seeds/levy_ledger_east_gate.py                │ ACTIVE_WRITE    │ Data literal at line 26+: every dict in the inline LEVY_DATA list has    │
│                                                       │                 │ "plan_id":"13195" but no "building_id". These records seeded from this   │
│                                                       │                 │ file are MISSING building_id. Migration fixes them in DB.                │
├──────────────────────────────────────────────────────────────────────────────────────────────────┼─────────────────┼─────────────────────────────────────────────────────────────────────────┤
│ backend/seeds/migrate_strata_sync_to_financial.py     │ COMPAT_SHIM     │ Lines 80, 104: writes both plan_id and building_id in $set. Correct.     │
├──────────────────────────────────────────────────────────────────────────────────────────────────┼─────────────────┼─────────────────────────────────────────────────────────────────────────┤
│ backend/seeds/seed_demo_enrichment.py                 │ COMPAT_SHIM     │ Lines 54-55, 103-104, 293-294, 342-343: always writes both plan_id and   │
│                                                       │                 │ building_id. Correct.                                                    │
├──────────────────────────────────────────────────────────────────────────────────────────────────┼─────────────────┼─────────────────────────────────────────────────────────────────────────┤
│ backend/seeds/seed_demo_finance.py                    │ ALIAS_READ      │ Line 27: queries by plan_id only (as filter). Also a COMPAT concern but  │
│                                                       │                 │ harmless since the DB shim in database.py handles the $or lookup.        │
├──────────────────────────────────────────────────────────────────────────────────────────────────┼─────────────────┼─────────────────────────────────────────────────────────────────────────┤
│ backend/seeds/snapshot_annual_levies.py               │ COMPAT_SHIM     │ Inline data literal: each record has BOTH plan_id and building_id as     │
│                                                       │                 │ generated from the live DB snapshot. No missing building_id.             │
├──────────────────────────────────────────────────────────────────────────────────────────────────┼─────────────────┼─────────────────────────────────────────────────────────────────────────┤
│ backend/services/financial_import_service.py          │ COMPAT_SHIM     │ Line 231: $set writes plan_id alongside building_id (line 229). Both     │
│                                                       │                 │ fields always present in the upsert payload. Correct.                    │
└──────────────────────────────────────────────────────────────────────────────────────────────────┴─────────────────┴─────────────────────────────────────────────────────────────────────────┘

ACTIVE_WRITE BUGS REQUIRING CODE FIXES (not fixed by this migration — migration only fixes DB data):
  1. backend/routers/reconciliation.py  lines 304-313, 327-331
     $set dict for levy_categories upsert and annual_levies insert includes "plan_id": building_id
     but does NOT include "building_id": building_id.  The building_id IS in the query filter
     (so the DB shim auto-injects it), but the document body on the DB side may still lack the field
     for documents created by an upsert (insert side of upsert).  Fix: add "building_id": building_id
     to both $set dicts alongside the existing "plan_id" entry.

  2. backend/seeds/enhanced_dashboard.py  lines 82, 91, 134, 150
     annual_levies and unit_levy_ledger inserts write only "plan_id": "13195" — no building_id.
     Fix: add "building_id": "13195" (or better, accept building_id as a parameter) to each insert doc.

  3. backend/seeds/levy_ledger_east_gate.py  line 150+
     Inline data literal omits building_id from every LEVY_DATA dict.
     Fix: add "building_id": "13195" to each dict in the LEVY_DATA list, or post-process before upsert.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

WHAT THIS MIGRATION DOES
  - Connects directly to MongoDB using motor (bypasses the TenantScopedDatabase
    shim so we can see the raw document fields).
  - Discovers all collection names dynamically.
  - Skips known global/system collections that are never tenant-scoped.
  - For each remaining collection, finds documents where:
      plan_id exists AND is non-null
      AND (building_id missing OR building_id is null)
  - Sets building_id = plan_id for each such document.
  - Logs counts per collection.
  - Is idempotent: re-running is safe (the filter guarantees already-fixed
    documents are not touched again).
  - --dry-run flag: reports counts without writing.

ROLLBACK
  Run migration_010_rollback.py to undo: it removes building_id from any
  document that still carries plan_id (i.e. was backfilled by this script).
  It will NOT remove building_id from documents that had it before migration.

Run:
    cd backend && python3 scripts/migrations/migration_010_backfill_building_id_from_plan_id.py
    cd backend && python3 scripts/migrations/migration_010_backfill_building_id_from_plan_id.py --dry-run
"""

import argparse
import asyncio
import os
import sys
from pathlib import Path

from dotenv import load_dotenv
from motor.motor_asyncio import AsyncIOMotorClient

backend_dir = Path(__file__).parent.parent.parent
sys.path.insert(0, str(backend_dir))
load_dotenv(backend_dir / ".env")

MONGO_URL = os.getenv("MONGO_URL")
DB_NAME = os.getenv("DB_NAME")

# Collections that are global / system-level and are never tenant-scoped.
# Skipping them prevents false positives (e.g. the "buildings" collection has
# a "plan_id" field that IS the building identifier, not an alias needing backfill).
GLOBAL_COLLECTIONS = {
    "buildings",
    "users",
    "roles",
    "site_settings",
    "feature_toggles",
    "system_logs",
    "system_events",
    # integration layer collections use tenant_id, not building_id
    "integration_inbox",
    "event_log",
    "mock_biller_allocations",
}


async def run(dry_run: bool = False) -> None:
    """Generated function header.

    Function: run
    Path: backend/scripts/migrations/migration_010_backfill_building_id_from_plan_id.py

    Note: Generated inventory header. Replace or expand this with reviewed business-purpose documentation before relying on it as source commentary.
    """
    client = AsyncIOMotorClient(MONGO_URL)
    db = client[DB_NAME]

    mode = "DRY-RUN" if dry_run else "LIVE"
    print(f"Migration 010 [{mode}] — backfill building_id from plan_id on db={DB_NAME!r}")
    print()

    # Discover all collection names dynamically — never hardcode a list.
    all_collections = sorted(await db.list_collection_names())

    tenant_collections = [c for c in all_collections if c not in GLOBAL_COLLECTIONS]

    print(f"Found {len(all_collections)} total collections; "
          f"scanning {len(tenant_collections)} tenant-scoped collections "
          f"(skipping {len(GLOBAL_COLLECTIONS)} global/system collections).")
    print()

    # Filter: plan_id exists and is not null, AND building_id is missing or null.
    missing_filter = {
        "plan_id": {"$exists": True, "$ne": None},
        "$or": [
            {"building_id": {"$exists": False}},
            {"building_id": None},
        ],
    }

    total_found = 0
    total_updated = 0
    results = []

    for coll_name in tenant_collections:
        coll = db[coll_name]
        count = await coll.count_documents(missing_filter)

        if count == 0:
            continue

        total_found += count
        results.append((coll_name, count))

        if dry_run:
            print(f"  [DRY-RUN] {coll_name}: {count} document(s) would be updated")
        else:
            # Use update_many with aggregation pipeline to set building_id = plan_id.
            # The aggregation $set form lets us reference the value of another field.
            result = await coll.update_many(
                missing_filter,
                [{"$set": {"building_id": "$plan_id"}}],
            )
            updated = result.modified_count
            total_updated += updated
            print(f"  {coll_name}: {count} matched → {updated} updated")

    print()

    if not results:
        print("No documents found with plan_id present and building_id missing. Nothing to do.")
    elif dry_run:
        print(f"DRY-RUN SUMMARY: {total_found} document(s) across "
              f"{len(results)} collection(s) would have building_id backfilled.")
        print()
        print("Collections that would be affected:")
        for coll_name, count in results:
            print(f"  {coll_name}: {count}")
    else:
        print(f"Migration 010 complete: {total_updated} document(s) updated across "
              f"{len(results)} collection(s).")

    client.close()


def parse_args() -> argparse.Namespace:
    """Generated function header.

    Function: parse_args
    Path: backend/scripts/migrations/migration_010_backfill_building_id_from_plan_id.py

    Note: Generated inventory header. Replace or expand this with reviewed business-purpose documentation before relying on it as source commentary.
    """
    parser = argparse.ArgumentParser(
        description="Migration 010: backfill building_id from plan_id for documents missing it."
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Count affected documents without writing any changes.",
    )
    return parser.parse_args()


if __name__ == "__main__":
    args = parse_args()
    asyncio.run(run(dry_run=args.dry_run))
