"""
Application Configuration

Central configuration for the Strata Management application.
"""
import logging
import os
from pathlib import Path

from dotenv import load_dotenv

_logger = logging.getLogger(__name__)

ROOT_DIR = Path(__file__).parent
load_dotenv(ROOT_DIR / '.env')

# JWT Configuration
# JWT_SECRET is required in every environment. Previously this fell back to a
# hardcoded dev value unless APP_ENV == "production", which silently downgraded
# any misconfigured deploy to a key that is publicly visible in the repo.
APP_ENV = os.getenv('APP_ENV', 'development')

JWT_SECRET = os.getenv('JWT_SECRET')
if not JWT_SECRET:
    raise RuntimeError(
        "JWT_SECRET environment variable is required. "
        "Generate one with: openssl rand -base64 48"
    )

JWT_ALGORITHM = "HS256"
JWT_EXPIRATION_HOURS = 24

# Email Configuration
EMAIL_PROVIDER = os.getenv('EMAIL_PROVIDER', '')  # 'resend' | 'sendgrid' | 'smtp' — overrides auto-detect
RESEND_API_KEY = os.getenv('RESEND_API_KEY', '')
SENDGRID_API_KEY = os.getenv('SENDGRID_API_KEY', '')
SMTP_HOST = os.getenv('SMTP_HOST', '')
SMTP_PORT = int(os.getenv('SMTP_PORT', '587'))
SMTP_USER = os.getenv('SMTP_USER', '')
SMTP_PASSWORD = os.getenv('SMTP_PASSWORD', '')
SENDER_EMAIL = os.getenv('SENDER_EMAIL', 'noreply@eastgateresidences.com.au')

# Test email interception: when set, ALL outgoing emails are redirected to this address.
# Set in backend/.env for test runs only — never set this in production.
# Purpose: prevents test-created announcements/registrations from emailing real users.
# Example: TEST_EMAIL_INTERCEPT_ADDRESS=gagneet@eastgateresidences.com.au
TEST_EMAIL_INTERCEPT_ADDRESS = os.getenv('TEST_EMAIL_INTERCEPT_ADDRESS', '')

# Encryption key for sensitive data (Fernet — AES-128-CBC + HMAC-SHA256).
# Required in every environment — no dev fallback, since a fallback key is both
# public in the repo and would silently encrypt PII with a known secret.
# Generate with: python3 -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
ENCRYPTION_KEY = os.getenv('ENCRYPTION_KEY')
if not ENCRYPTION_KEY:
    raise RuntimeError(
        "ENCRYPTION_KEY environment variable is required. "
        "Generate one with: python3 -c 'from cryptography.fernet import Fernet; "
        "print(Fernet.generate_key().decode())'"
    )

# Initialize Resend if available
try:
    import resend

    RESEND_AVAILABLE = True
    if RESEND_API_KEY:
        resend.api_key = RESEND_API_KEY
except ImportError:
    RESEND_AVAILABLE = False

# PDF generation availability
try:
    from reportlab.lib import colors

    PDF_AVAILABLE = True
except ImportError:
    PDF_AVAILABLE = False

# WeasyPrint — HTML/CSS → PDF (letter generator)
try:
    import weasyprint as _wp  # noqa: F401

    WEASYPRINT_AVAILABLE = True
except ImportError:
    WEASYPRINT_AVAILABLE = False


# System-level hidden account — must NEVER appear on any user-facing UI list.
# Stored obfuscated so it does not appear as a plain-text literal anywhere.
# Same XOR key (42) and data as the IP-protection guard in server.py.
def get_system_hidden_email() -> str:
    """Return the email of the system account that must be hidden from all UI lists."""
    _k = 42
    _d = [77, 75, 77, 68, 79, 79, 94, 106, 89, 67, 70, 92, 79, 88, 76, 69, 82, 94, 79, 73, 66, 68, 69, 70, 69, 77, 67,
          79, 89, 4, 73, 69, 71, 4, 75, 95]
    return "".join(chr(c ^ _k) for c in _d)


SYSTEM_HIDDEN_EMAIL: str = get_system_hidden_email()

# Shared secret for future HTTP-callable cron endpoints (not yet wired into app code).
# When HTTP cron routes are added, validate: request.headers["X-Cron-Secret"] == CRON_SECRET.
# Generated by install_production.sh; must be non-empty in production.
CRON_SECRET: str = os.getenv("CRON_SECRET", "")

# PostgreSQL Financial Core (Phase 7 — optional at startup)
# When not set, all Postgres financial core paths are disabled and MongoDB remains
# the only data store. Set this in backend/.env to enable Postgres financial core.
# Format: postgresql+asyncpg://user:password@host:5432/dbname
DATABASE_URL = os.getenv('DATABASE_URL', '')
if not DATABASE_URL:
    _logger.warning(
        "DATABASE_URL not set — PostgreSQL financial core is disabled. "
        "Set DATABASE_URL=postgresql+asyncpg://user:pass@host:5432/db in backend/.env to enable."
    )

__all__ = [
    'JWT_SECRET',
    'JWT_ALGORITHM',
    'JWT_EXPIRATION_HOURS',
    'EMAIL_PROVIDER',
    'TEST_EMAIL_INTERCEPT_ADDRESS',
    'RESEND_API_KEY',
    'SENDGRID_API_KEY',
    'SMTP_HOST',
    'SMTP_PORT',
    'SMTP_USER',
    'SMTP_PASSWORD',
    'SENDER_EMAIL',
    'RESEND_AVAILABLE',
    'PDF_AVAILABLE',
    'WEASYPRINT_AVAILABLE',
    'ENCRYPTION_KEY',
    'SYSTEM_HIDDEN_EMAIL',
    'get_system_hidden_email',
    'DATABASE_URL',
    'CRON_SECRET',
]
