#!/usr/bin/env python3
# @featuretrace:owner-activation — Mark restored owners unclaimed and send their activation links.
# Layer: script
# Data flow: users (building-scoped) -> mark_unclaimed + issue_activation -> send_email_async
#            -> outbound queue -> operator review -> owner.
# Related: backend/services/owner_activation_service.py
#          backend/routers/auth.py
#          tasks/GAP-COMMS-003-outbound-message-queue-and-activation.md
"""Send activation invitations to owners who have never claimed their account.

    python3 scripts/send_owner_activation_invites.py --building 13195 --dry-run
    python3 scripts/send_owner_activation_invites.py --building 13195 --apply
    python3 scripts/send_owner_activation_invites.py --building 13195 --apply --limit 5

Dry-run is the default and --apply is required, because this both mutates production
accounts (setting requires_activation, which stops a sign-in) and generates outgoing
mail. --limit exists so the first real run can be a handful of addresses that a person
reads in the queue console before the remaining hundred follow.

Nothing is transmitted directly. Messages enter the outbound queue and wait for review
like any other mail, so a mistake here is visible and droppable rather than delivered.

Selection: owners with no password_hash in MongoDB — accounts that exist because they
were imported or restored, and that nobody has ever set a password on. Anyone who has
signed in is skipped, because marking them unclaimed would lock out a working account.
"""

import argparse
import asyncio
import logging
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from dotenv import load_dotenv  # noqa: E402

load_dotenv(ROOT / ".env")

from database import db  # noqa: E402
from request_context import set_ctx_building_id  # noqa: E402
from services.owner_activation_service import (  # noqa: E402
    build_activation_email,
    issue_activation,
    mark_unclaimed,
)

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
logger = logging.getLogger("activation_invites")


# Placeholder identities generated by ownership transfers and historical
# reconstruction. They are rows in a ledger, not people with inboxes, and inviting them
# would queue mail nobody can act on while making the console harder to read.
_SYNTHETIC_EMAIL = re.compile(r"owner-transfer[.+]|historical|^developer[.+]", re.I)


async def candidates(building_id: str) -> tuple[list[dict], list[dict]]:
    """Split owners who have never set a password into real people and placeholders.

    A present password_hash means somebody has signed in (or an admin set one), and
    flagging those would lock a working account out — the opposite of the intent.

    Both halves are returned so the caller can REPORT what it skipped. Silently
    dropping 20 of 103 rows would read as "103 owners invited" in a log nobody
    reconciles.
    """
    real: list[dict] = []
    synthetic: list[dict] = []
    async for u in db.users.find({"role": "owner"}):
        if u.get("password_hash") or u.get("hashed_password"):
            continue
        if u.get("status") == "archived":
            continue
        email = (u.get("email") or "").strip()
        if not email:
            continue
        (synthetic if _SYNTHETIC_EMAIL.search(email) else real).append(u)
    return real, synthetic


async def main(args) -> int:
    set_ctx_building_id(args.building)

    building = await db.buildings.find_one({"building_id": args.building}) or {}
    building_name = building.get("name") or f"Building {args.building}"

    people, synthetic = await candidates(args.building)
    mode = "APPLY" if args.apply else "DRY-RUN"
    logger.info("%s — %s owner(s) awaiting activation in %s",
                mode, len(people), building_name)
    if synthetic:
        logger.info("  skipping %s placeholder identit%s (ownership-transfer and "
                    "historical stubs, not real inboxes)",
                    len(synthetic), "y" if len(synthetic) == 1 else "ies")
    if args.limit:
        people = people[: args.limit]
        logger.info("  --limit %s: processing the first %s of them",
                    args.limit, len(people))

    sent = 0
    for user in people:
        email = user["email"]
        if not args.apply:
            logger.info("  [dry-run] would invite %s (%s)", email, user.get("unit_number") or "-")
            continue

        # Flag first. If the send fails afterwards the account is merely unclaimed,
        # which is the safe direction; flagging after sending would leave a window
        # where a live link points at an account that still accepts the old password.
        await mark_unclaimed(email)

        link = await issue_activation(user, building_id=args.building)
        if not link:
            logger.warning("  skipped %s — could not issue a link", email)
            continue

        html, text = build_activation_email(user, link, building_name)

        from utils.email import send_email_async

        result = await send_email_async(
            email, f"Activate your {building_name} owner account", html, text,
            context="owner_activation", building_id=args.building, category="automated",
        )
        state = "queued" if result.get("queued") else (
            "sent" if result.get("success") else result.get("provider", "not sent"))
        logger.info("  %s -> %s", email, state)
        sent += 1

    logger.info("%s complete: %s processed", mode, sent if args.apply else len(people))
    if not args.apply:
        logger.info("Re-run with --apply to mark these accounts unclaimed and queue "
                    "their invitations.")
    return 0


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--building", required=True, help="building_id, e.g. 13195")
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--dry-run", action="store_true")
    g.add_argument("--apply", action="store_true")
    ap.add_argument("--limit", type=int, default=0,
                    help="Process at most N owners — use for a small first batch")
    sys.exit(asyncio.run(main(ap.parse_args())))
