"""
Navigation configs — per-role sidebar items for all 10 roles.

Generated from live DB on 2026-04-01. DO NOT EDIT MANUALLY.
Regenerate with:  cd backend && venv/bin/python3 ../scripts/db/snapshot_all.py

NOTE (GAP-FE-001, 2026-08-10): the 12 stale nav `route` values that pointed at
non-existent App Router pages (real-estate/*, maintenance/work-orders,
financials/purchase-orders, compliance/my-compliance, community/*, admin/keys,
community/guest-stay) were hand-synced here to match the same 404 fixes applied
to navigation_configs.py, so restoring this snapshot cannot reintroduce the
broken links. The next live regen reproduces these values from the seeded DB.
"""
import asyncio
import os
from pathlib import Path

from dotenv import load_dotenv
from pymongo import AsyncMongoClient

ROOT_DIR = Path(__file__).parent.parent
load_dotenv(ROOT_DIR / ".env")

LEGACY_NAV_ROLES = ("chairman", "reception")

NAVIGATION_CONFIGS = [{'role': 'strata_admin', 'advanced_items': [
    {'id': 'finance', 'label': 'Finance oversight', 'route': '/financials', 'icon': 'DollarSign',
     'feature_flag': '', 'permission_flag': '', 'badge_source': '', 'priority': 1,
     'discovery_hint': 'Portfolio finance position', 'nudge_trigger': ''},
    {'id': 'compliance', 'label': 'Compliance oversight', 'route': '/compliance', 'icon': 'ShieldCheck',
     'feature_flag': '', 'permission_flag': '', 'badge_source': 'compliance_overdue', 'priority': 2,
     'discovery_hint': '', 'nudge_trigger': ''},
    {'id': 'maintenance', 'label': 'Maintenance oversight', 'route': '/maintenance', 'icon': 'Wrench',
     'feature_flag': '', 'permission_flag': '', 'badge_source': 'requests_overdue', 'priority': 3,
     'discovery_hint': '', 'nudge_trigger': ''},
    {'id': 'workflows', 'label': 'Workflows', 'route': '/admin/workflows', 'icon': 'GitBranch',
     'feature_flag': 'workflow_governance', 'permission_flag': '', 'badge_source': '', 'priority': 4,
     'discovery_hint': 'See which automations ran today', 'nudge_trigger': ''},
    {'id': 'building-onboarding', 'label': 'Onboard Building', 'route': '/admin/portfolio/onboard',
     'icon': 'ClipboardCheck', 'feature_flag': 'building_onboarding', 'permission_flag': '', 'badge_source': '',
     'priority': 5, 'discovery_hint': 'Run the full scheme onboarding workflow', 'nudge_trigger': ''},
    {'id': 'quick-building-setup', 'label': 'Quick Building Setup', 'route': '/admin/buildings/onboard',
     'icon': 'Building2', 'feature_flag': 'building_onboarding', 'permission_flag': '', 'badge_source': '',
     'priority': 6, 'discovery_hint': 'Create a scheme shell and import a Strata Roll CSV', 'nudge_trigger': ''},
    {'id': 'financial-onboarding', 'label': 'Financial Onboarding',
     'route': '/admin/financial-onboarding', 'icon': 'Upload',
     'feature_flag': 'historical_financial_reconstruction', 'permission_flag': 'can_manage_finances',
     'badge_source': '', 'priority': 7,
     'discovery_hint': 'Complete historical financial onboarding through Demo Bank staging', 'nudge_trigger': ''},
    {'id': 'levies', 'label': 'Levy management', 'route': '/financials/levy-payments', 'icon': 'CreditCard',
     'feature_flag': '', 'permission_flag': '', 'badge_source': '', 'priority': 8,
     'discovery_hint': '', 'nudge_trigger': ''},
    {'id': 'meetings', 'label': 'Meetings', 'route': '/governance/meetings', 'icon': 'Calendar',
     'feature_flag': '', 'permission_flag': '', 'badge_source': '', 'priority': 9,
     'discovery_hint': '', 'nudge_trigger': ''},
    {'id': 'bylaws', 'label': 'By-laws', 'route': '/governance/bylaws', 'icon': 'BookOpen', 'feature_flag': '',
     'permission_flag': '', 'badge_source': '', 'priority': 10, 'discovery_hint': '', 'nudge_trigger': ''},
    {'id': 'documents', 'label': 'Documents', 'route': '/documents', 'icon': 'FolderOpen',
     'feature_flag': '', 'permission_flag': '', 'badge_source': '', 'priority': 11,
     'discovery_hint': '', 'nudge_trigger': ''},
    {'id': 'insurance', 'label': 'Insurance', 'route': '/insurance', 'icon': 'Shield',
     'feature_flag': '', 'permission_flag': '', 'badge_source': '', 'priority': 12,
     'discovery_hint': '', 'nudge_trigger': ''},
    {'id': 'gst-bas-ledger', 'label': 'GST & BAS Ledger', 'route': '/admin/gst-bas-ledger',
     'icon': 'Receipt', 'feature_flag': 'gst_bas_ledger', 'permission_flag': 'can_manage_finances',
     'badge_source': '', 'priority': 13, 'discovery_hint': 'BAS worksheet, output tax, input tax credits',
     'nudge_trigger': ''}], 'created_at': '2026-04-01T05:45:53.074005+00:00', 'id': 'nav-strata_admin', 'simple_items': [
    {'id': 'dashboard', 'label': 'Organisation dashboard', 'route': '/dashboard', 'icon': 'LayoutDashboard',
     'feature_flag': '', 'permission_flag': '', 'badge_source': '', 'priority': 1},
    {'id': 'portfolio', 'label': 'Portfolio', 'route': '/management/portfolio', 'icon': 'Building2',
     'feature_flag': 'portfolio_dashboard', 'permission_flag': '', 'badge_source': '', 'priority': 2},
    {'id': 'users', 'label': 'Users & roles', 'route': '/admin/users', 'icon': 'UserCog',
     'feature_flag': '', 'permission_flag': 'can_manage_users', 'badge_source': '', 'priority': 3},
    {'id': 'reports', 'label': 'Reports', 'route': '/reports', 'icon': 'FileText',
     'feature_flag': '', 'permission_flag': '', 'badge_source': '', 'priority': 4},
    {'id': 'settings', 'label': 'Organisation settings', 'route': '/settings', 'icon': 'Settings',
     'feature_flag': '', 'permission_flag': 'can_manage_settings', 'badge_source': '', 'priority': 5}],
                       'updated_at': '2026-04-01T10:21:42.315393+00:00', 'version': 1}, {'role': 'ec_member',
                                                                                         'advanced_items': [
                                                                                             {'id': 'finance',
                                                                                              'label': 'Finance',
                                                                                              'route': '/financials',
                                                                                              'icon': 'DollarSign',
                                                                                              'feature_flag': '',
                                                                                              'permission_flag': '',
                                                                                              'badge_source': '',
                                                                                              'priority': 1,
                                                                                              'discovery_hint': 'See full financial position',
                                                                                              'nudge_trigger': ''},
                                                                                             {'id': 'bylaws',
                                                                                              'label': 'By-laws',
                                                                                              'route': '/governance/bylaws',
                                                                                              'icon': 'BookOpen',
                                                                                              'feature_flag': '',
                                                                                              'permission_flag': '',
                                                                                              'badge_source': '',
                                                                                              'priority': 2,
                                                                                              'discovery_hint': '',
                                                                                              'nudge_trigger': ''},
                                                                                             {'id': 'compliance',
                                                                                              'label': 'Compliance',
                                                                                              'route': '/compliance',
                                                                                              'icon': 'ShieldCheck',
                                                                                              'feature_flag': '',
                                                                                              'permission_flag': '',
                                                                                              'badge_source': 'compliance_overdue',
                                                                                              'priority': 3,
                                                                                              'discovery_hint': '',
                                                                                              'nudge_trigger': ''},
                                                                                             {'id': 'documents',
                                                                                              'label': 'Documents',
                                                                                              'route': '/documents',
                                                                                              'icon': 'FolderOpen',
                                                                                              'feature_flag': '',
                                                                                              'permission_flag': '',
                                                                                              'badge_source': '',
                                                                                              'priority': 4,
                                                                                              'discovery_hint': '',
                                                                                              'nudge_trigger': ''},
                                                                                             {'id': 'proposals',
                                                                                              'label': 'Proposals',
                                                                                              'route': '/governance/proposals',
                                                                                              'icon': 'Vote',
                                                                                              'feature_flag': '',
                                                                                              'permission_flag': '',
                                                                                              'badge_source': 'proposals_open_vote',
                                                                                              'priority': 5,
                                                                                              'discovery_hint': '',
                                                                                              'nudge_trigger': ''},
                                                                                             {'id': 'owner-view',
                                                                                              'label': 'My owner view',
                                                                                              'route': '/owner-view',
                                                                                              'icon': 'Home',
                                                                                              'feature_flag': '',
                                                                                              'permission_flag': '',
                                                                                              'badge_source': '',
                                                                                              'priority': 6,
                                                                                              'discovery_hint': 'See your own levy and property data',
                                                                                              'nudge_trigger': ''}],
                                                                                         'created_at': '2026-04-01T05:45:53.074005+00:00',
                                                                                         'id': 'nav-ec_member',
                                                                                         'simple_items': [
                                                                                             {'id': 'dashboard',
                                                                                              'label': 'Dashboard',
                                                                                              'route': '/dashboard',
                                                                                              'icon': 'LayoutDashboard',
                                                                                              'feature_flag': '',
                                                                                              'permission_flag': '',
                                                                                              'badge_source': '',
                                                                                              'priority': 1},
                                                                                             {'id': 'approvals',
                                                                                              'label': 'Approvals',
                                                                                              'route': '/requests/my-approvals',
                                                                                              'icon': 'CheckSquare',
                                                                                              'feature_flag': '',
                                                                                              'permission_flag': '',
                                                                                              'badge_source': 'approvals_pending',
                                                                                              'priority': 2},
                                                                                             {'id': 'meetings',
                                                                                              'label': 'Meetings',
                                                                                              'route': '/governance/meetings',
                                                                                              'icon': 'Calendar',
                                                                                              'feature_flag': '',
                                                                                              'permission_flag': '',
                                                                                              'badge_source': '',
                                                                                              'priority': 3},
                                                                                             {'id': 'maintenance',
                                                                                              'label': 'Maintenance',
                                                                                              'route': '/maintenance',
                                                                                              'icon': 'Wrench',
                                                                                              'feature_flag': '',
                                                                                              'permission_flag': '',
                                                                                              'badge_source': '',
                                                                                              'priority': 4},
                                                                                             {'id': 'community',
                                                                                              'label': 'Community',
                                                                                              'route': '/community',
                                                                                              'icon': 'Users',
                                                                                              'feature_flag': '',
                                                                                              'permission_flag': '',
                                                                                              'badge_source': '',
                                                                                              'priority': 5}],
                                                                                         'updated_at': '2026-04-01T10:21:42.315393+00:00',
                                                                                         'version': 1},
                      {'role': 'guest', 'advanced_items': [
                          {'id': 'directory', 'label': 'Resident directory', 'route': '/community/directory',
                           'icon': 'Users', 'feature_flag': '', 'permission_flag': '', 'badge_source': '',
                           'priority': 1, 'discovery_hint': '', 'nudge_trigger': ''},
                          {'id': 'events', 'label': 'Community events', 'route': '/community/events',
                           'icon': 'Calendar', 'feature_flag': '', 'permission_flag': '', 'badge_source': '',
                           'priority': 2, 'discovery_hint': '', 'nudge_trigger': ''},
                          {'id': 'chat', 'label': 'Chat', 'route': '/community/chat', 'icon': 'MessageCircle',
                           'feature_flag': '', 'permission_flag': '', 'badge_source': '', 'priority': 3,
                           'discovery_hint': '', 'nudge_trigger': ''}],
                       'created_at': '2026-04-01T05:45:53.074005+00:00', 'id': 'nav-guest', 'simple_items': [
                          {'id': 'home', 'label': 'Home', 'route': '/dashboard', 'icon': 'Home', 'feature_flag': '',
                           'permission_flag': '', 'badge_source': '', 'priority': 1},
                          {'id': 'notices', 'label': 'Notices', 'route': '/community/notices', 'icon': 'Bell',
                           'feature_flag': '', 'permission_flag': '', 'badge_source': 'notices_unread', 'priority': 2},
                          {'id': 'requests', 'label': 'Requests', 'route': '/requests',
                           'icon': 'MessageSquare', 'feature_flag': '', 'permission_flag': '', 'badge_source': '',
                           'priority': 3},
                          {'id': 'bookings', 'label': 'Bookings', 'route': '/community/bookings', 'icon': 'BookMarked',
                           'feature_flag': '', 'permission_flag': '', 'badge_source': '', 'priority': 4},
                          {'id': 'my-stay', 'label': 'My stay', 'route': '/community/bookings/my-stay', 'icon': 'Calendar',
                           'feature_flag': '', 'permission_flag': '', 'badge_source': '', 'priority': 5}],
                       'updated_at': '2026-04-01T10:21:42.315393+00:00', 'version': 1}, {'role': 'owner',
                                                                                         'advanced_items': [
                                                                                             {'id': 'my-finances',
                                                                                              'label': 'My finances',
                                                                                              'route': '/financials/my-finances',
                                                                                              'icon': 'PieChart',
                                                                                              'feature_flag': 'my_finances',
                                                                                              'permission_flag': '',
                                                                                              'badge_source': '',
                                                                                              'priority': 1,
                                                                                              'discovery_hint': 'See exactly where your levy goes',
                                                                                              'nudge_trigger': 'levy_page_visits_7d_gte_3'},
                                                                                             {'id': 'documents',
                                                                                              'label': 'Documents',
                                                                                              'route': '/documents',
                                                                                              'icon': 'FolderOpen',
                                                                                              'feature_flag': '',
                                                                                              'permission_flag': '',
                                                                                              'badge_source': '',
                                                                                              'priority': 3,
                                                                                              'discovery_hint': '',
                                                                                              'nudge_trigger': ''},
                                                                                             {'id': 'community',
                                                                                              'label': 'Community',
                                                                                              'route': '/community',
                                                                                              'icon': 'Users',
                                                                                              'feature_flag': '',
                                                                                              'permission_flag': '',
                                                                                              'badge_source': '',
                                                                                              'priority': 4,
                                                                                              'discovery_hint': '',
                                                                                              'nudge_trigger': ''},
                                                                                             {'id': 'savings',
                                                                                              'label': 'Savings tracker',
                                                                                              'route': '/financials/savings',
                                                                                              'icon': 'PiggyBank',
                                                                                              'feature_flag': 'volunteer_credits',
                                                                                              'permission_flag': '',
                                                                                              'badge_source': '',
                                                                                              'priority': 5,
                                                                                              'discovery_hint': 'See what your community saved this year',
                                                                                              'nudge_trigger': 'savings_event_created_last_7d'},
                                                                                             {'id': 'marketplace',
                                                                                              'label': 'Marketplace',
                                                                                              'route': '/community/marketplace',
                                                                                              'icon': 'ShoppingBag',
                                                                                              'feature_flag': '',
                                                                                              'permission_flag': '',
                                                                                              'badge_source': '',
                                                                                              'priority': 6,
                                                                                              'discovery_hint': '',
                                                                                              'nudge_trigger': ''},
                                                                                             {'id': 'events',
                                                                                              'label': 'Events',
                                                                                              'route': '/community/events',
                                                                                              'icon': 'Calendar',
                                                                                              'feature_flag': '',
                                                                                              'permission_flag': '',
                                                                                              'badge_source': '',
                                                                                              'priority': 7,
                                                                                              'discovery_hint': '',
                                                                                              'nudge_trigger': ''},
                                                                                             {'id': 'bookings',
                                                                                              'label': 'Bookings',
                                                                                              'route': '/community/bookings',
                                                                                              'icon': 'BookMarked',
                                                                                              'feature_flag': '',
                                                                                              'permission_flag': '',
                                                                                              'badge_source': '',
                                                                                              'priority': 8,
                                                                                              'discovery_hint': '',
                                                                                              'nudge_trigger': ''}],
                                                                                         'created_at': '2026-04-01T05:45:53.074005+00:00',
                                                                                         'id': 'nav-owner',
                                                                                         'simple_items': [{'id': 'home',
                                                                                                           'label': 'Home',
                                                                                                           'route': '/dashboard',
                                                                                                           'icon': 'Home',
                                                                                                           'feature_flag': '',
                                                                                                           'permission_flag': '',
                                                                                                           'badge_source': '',
                                                                                                           'priority': 1},
                                                                                                          {
                                                                                                              'id': 'my-levies',
                                                                                                              'label': 'My levies',
                                                                                                              'route': '/financials/levy-payments',
                                                                                                              'icon': 'CreditCard',
                                                                                                              'feature_flag': '',
                                                                                                              'permission_flag': '',
                                                                                                              'badge_source': 'levy_due_soon',
                                                                                                              'priority': 2},
                                                                                                          {
                                                                                                              'id': 'requests',
                                                                                                              'label': 'Requests',
                                                                                                              'route': '/requests/new',
                                                                                                              'icon': 'MessageSquare',
                                                                                                              'feature_flag': 'smart_requests',
                                                                                                              'permission_flag': '',
                                                                                                              'badge_source': 'requests_new',
                                                                                                              'priority': 3},
                                                                                                          {
                                                                                                              'id': 'notices',
                                                                                                              'label': 'Notices',
                                                                                                              'route': '/community/notices',
                                                                                                              'icon': 'Bell',
                                                                                                              'feature_flag': '',
                                                                                                              'permission_flag': '',
                                                                                                              'badge_source': 'notices_unread',
                                                                                                              'priority': 4},
                                                                                                          {'id': 'vote',
                                                                                                           'label': 'Vote',
                                                                                                           'route': '/governance/proposals',
                                                                                                           'icon': 'Vote',
                                                                                                           'feature_flag': '',
                                                                                                           'permission_flag': '',
                                                                                                           'badge_source': 'proposals_open_vote',
                                                                                                           'priority': 5}],
                                                                                         'updated_at': '2026-04-01T10:21:42.315393+00:00',
                                                                                         'version': 1},
                      {'role': 'real_estate_agent', 'advanced_items': [
                          {'id': 'lease-renewals', 'label': 'Lease renewals', 'route': '/real-estate/renewals',
                           'icon': 'RefreshCw', 'feature_flag': '', 'permission_flag': '', 'badge_source': '',
                           'priority': 1, 'discovery_hint': 'Track upcoming lease expiries', 'nudge_trigger': ''},
                          {'id': 'inspections', 'label': 'Inspections', 'route': '/owner-hub/inspections',
                           'icon': 'ClipboardCheck', 'feature_flag': '', 'permission_flag': '', 'badge_source': '',
                           'priority': 2, 'discovery_hint': '', 'nudge_trigger': ''},
                          {'id': 'documents', 'label': 'Documents', 'route': '/documents',
                           'icon': 'FolderOpen', 'feature_flag': '', 'permission_flag': '', 'badge_source': '',
                           'priority': 3, 'discovery_hint': '', 'nudge_trigger': ''},
                          {'id': 'owner-reports', 'label': 'Owner reports', 'route': '/reports',
                           'icon': 'FileText', 'feature_flag': '', 'permission_flag': '', 'badge_source': '',
                           'priority': 4, 'discovery_hint': '', 'nudge_trigger': ''}],
                       'created_at': '2026-04-01T05:45:53.074005+00:00', 'id': 'nav-real_estate_agent',
                       'simple_items': [
                           {'id': 'dashboard', 'label': 'Dashboard', 'route': '/dashboard', 'icon': 'LayoutDashboard',
                            'feature_flag': '', 'permission_flag': '', 'badge_source': '', 'priority': 1},
                           {'id': 'my-tenants', 'label': 'My tenants', 'route': '/real-estate',
                            'icon': 'Users', 'feature_flag': '', 'permission_flag': '', 'badge_source': '',
                            'priority': 2},
                           {'id': 'maintenance', 'label': 'Maintenance', 'route': '/maintenance',
                            'icon': 'Wrench', 'feature_flag': '', 'permission_flag': '', 'badge_source': '',
                            'priority': 3},
                           {'id': 'notices', 'label': 'Notices', 'route': '/community/notices', 'icon': 'Bell',
                            'feature_flag': '', 'permission_flag': '', 'badge_source': 'notices_unread', 'priority': 4},
                           {'id': 'certificates', 'label': 'Certificates', 'route': '/requests/rental-certificates',
                            'icon': 'Award', 'feature_flag': '', 'permission_flag': '', 'badge_source': '',
                            'priority': 5}], 'updated_at': '2026-04-01T10:21:42.315393+00:00', 'version': 1},
                      {'role': 'admin_staff', 'advanced_items': [
                          {'id': 'requests-log', 'label': 'Requests log', 'route': '/requests',
                           'icon': 'MessageSquare', 'feature_flag': '', 'permission_flag': '', 'badge_source': '',
                           'priority': 1, 'discovery_hint': '', 'nudge_trigger': ''},
                          {'id': 'keys', 'label': 'Key register', 'route': '/requests/access-control', 'icon': 'Key',
                           'feature_flag': '', 'permission_flag': '', 'badge_source': '', 'priority': 2,
                           'discovery_hint': '', 'nudge_trigger': ''},
                          {'id': 'moves', 'label': 'Move in/out', 'route': '/community/bookings/moves', 'icon': 'ArrowLeftRight',
                           'feature_flag': '', 'permission_flag': '', 'badge_source': '', 'priority': 3,
                           'discovery_hint': '', 'nudge_trigger': ''},
                          {'id': 'directory', 'label': 'Resident directory', 'route': '/community/directory',
                           'icon': 'Users', 'feature_flag': '', 'permission_flag': '', 'badge_source': '',
                           'priority': 4, 'discovery_hint': '', 'nudge_trigger': ''},
                          {'id': 'incidents', 'label': 'Incident report', 'route': '/requests/new',
                           'icon': 'AlertTriangle', 'feature_flag': '', 'permission_flag': '', 'badge_source': '',
                           'priority': 5, 'discovery_hint': '', 'nudge_trigger': ''}],
                       'created_at': '2026-04-01T05:45:53.074005+00:00', 'id': 'nav-admin_staff', 'simple_items': [
                          {'id': 'dashboard', 'label': 'Dashboard', 'route': '/dashboard', 'icon': 'LayoutDashboard',
                           'feature_flag': '', 'permission_flag': '', 'badge_source': '', 'priority': 1},
                          {'id': 'parcels', 'label': 'Parcels', 'route': '/community/parcels', 'icon': 'Package',
                           'feature_flag': '', 'permission_flag': '', 'badge_source': 'parcels_waiting', 'priority': 2},
                          {'id': 'visitors', 'label': 'Visitors', 'route': '/community/bookings/visitors', 'icon': 'UserCheck',
                           'feature_flag': '', 'permission_flag': '', 'badge_source': '', 'priority': 3},
                          {'id': 'bookings', 'label': 'Bookings', 'route': '/community/bookings', 'icon': 'BookMarked',
                           'feature_flag': '', 'permission_flag': '', 'badge_source': '', 'priority': 4},
                          {'id': 'notices', 'label': 'Notices', 'route': '/community/notices', 'icon': 'Bell',
                           'feature_flag': '', 'permission_flag': '', 'badge_source': 'notices_unread', 'priority': 5}],
                       'updated_at': '2026-04-01T10:21:42.315393+00:00', 'version': 1}, {'role': 'service_provider',
                                                                                         'advanced_items': [
                                                                                             {'id': 'compliance-docs',
                                                                                              'label': 'My compliance docs',
                                                                                              'route': '/compliance',
                                                                                              'icon': 'ShieldCheck',
                                                                                              'feature_flag': '',
                                                                                              'permission_flag': '',
                                                                                              'badge_source': '',
                                                                                              'priority': 1,
                                                                                              'discovery_hint': 'Keep insurances and licences current',
                                                                                              'nudge_trigger': ''},
                                                                                             {'id': 'purchase-orders',
                                                                                              'label': 'Purchase orders',
                                                                                              'route': '/maintenance/purchase-orders',
                                                                                              'icon': 'ShoppingCart',
                                                                                              'feature_flag': '',
                                                                                              'permission_flag': '',
                                                                                              'badge_source': '',
                                                                                              'priority': 2,
                                                                                              'discovery_hint': '',
                                                                                              'nudge_trigger': ''},
                                                                                             {'id': 'schedule',
                                                                                              'label': 'Schedule',
                                                                                              'route': '/maintenance/schedule',
                                                                                              'icon': 'Calendar',
                                                                                              'feature_flag': '',
                                                                                              'permission_flag': '',
                                                                                              'badge_source': '',
                                                                                              'priority': 3,
                                                                                              'discovery_hint': '',
                                                                                              'nudge_trigger': ''}],
                                                                                         'created_at': '2026-04-01T05:45:53.074005+00:00',
                                                                                         'id': 'nav-service_provider',
                                                                                         'simple_items': [
                                                                                             {'id': 'dashboard',
                                                                                              'label': 'Dashboard',
                                                                                              'route': '/dashboard',
                                                                                              'icon': 'LayoutDashboard',
                                                                                              'feature_flag': '',
                                                                                              'permission_flag': '',
                                                                                              'badge_source': '',
                                                                                              'priority': 1},
                                                                                             {'id': 'my-work-orders',
                                                                                              'label': 'My work orders',
                                                                                              'route': '/maintenance/work-orders',
                                                                                              'icon': 'Wrench',
                                                                                              'feature_flag': '',
                                                                                              'permission_flag': '',
                                                                                              'badge_source': '',
                                                                                              'priority': 2},
                                                                                             {'id': 'invoices',
                                                                                              'label': 'Invoices',
                                                                                              'route': '/financials/invoices',
                                                                                              'icon': 'FileText',
                                                                                              'feature_flag': '',
                                                                                              'permission_flag': '',
                                                                                              'badge_source': '',
                                                                                              'priority': 3},
                                                                                             {'id': 'documents',
                                                                                              'label': 'Documents',
                                                                                              'route': '/documents',
                                                                                              'icon': 'FolderOpen',
                                                                                              'feature_flag': '',
                                                                                              'permission_flag': '',
                                                                                              'badge_source': '',
                                                                                              'priority': 4},
                                                                                             {'id': 'profile',
                                                                                              'label': 'Profile',
                                                                                              'route': '/profile',
                                                                                              'icon': 'User',
                                                                                              'feature_flag': '',
                                                                                              'permission_flag': '',
                                                                                              'badge_source': '',
                                                                                              'priority': 5}],
                                                                                         'updated_at': '2026-04-01T10:21:42.315393+00:00',
                                                                                         'version': 1},
                      {'role': 'strata_manager', 'advanced_items': [
                          {'id': 'portfolio', 'label': 'Portfolio', 'route': '/management/portfolio',
                           'icon': 'Building2', 'feature_flag': 'portfolio_dashboard', 'permission_flag': '',
                           'badge_source': '', 'priority': 1, 'discovery_hint': 'All buildings in one view',
                           'nudge_trigger': 'multiple_buildings_accessible'},
                          {'id': 'building-onboarding', 'label': 'Onboard Building',
                           'route': '/admin/portfolio/onboard', 'icon': 'ClipboardCheck',
                           'feature_flag': 'building_onboarding', 'permission_flag': '', 'badge_source': '',
                           'priority': 2, 'discovery_hint': 'Run the full scheme onboarding workflow',
                           'nudge_trigger': ''},
                          {'id': 'quick-building-setup', 'label': 'Quick Building Setup',
                           'route': '/admin/buildings/onboard', 'icon': 'Building2',
                           'feature_flag': 'building_onboarding', 'permission_flag': '', 'badge_source': '',
                           'priority': 3, 'discovery_hint': 'Create a scheme shell and import a Strata Roll CSV',
                           'nudge_trigger': ''},
                          {'id': 'financial-onboarding', 'label': 'Financial Onboarding',
                           'route': '/admin/financial-onboarding', 'icon': 'Upload',
                           'feature_flag': 'historical_financial_reconstruction',
                           'permission_flag': 'can_manage_finances', 'badge_source': '', 'priority': 4,
                           'discovery_hint': 'Complete historical financial onboarding through Demo Bank staging',
                           'nudge_trigger': ''},
                          {'id': 'workflows', 'label': 'Workflows', 'route': '/admin/workflows',
                           'icon': 'GitBranch', 'feature_flag': 'workflow_governance', 'permission_flag': '',
                           'badge_source': '', 'priority': 5, 'discovery_hint': 'See which automations ran today',
                           'nudge_trigger': 'open_requests_gte_5'},
                          {'id': 'users', 'label': 'Users & roles', 'route': '/admin/users', 'icon': 'UserCog',
                           'feature_flag': '', 'permission_flag': 'can_manage_users', 'badge_source': '', 'priority': 6,
                           'discovery_hint': '', 'nudge_trigger': ''},
                          {'id': 'reports', 'label': 'Reports', 'route': '/reports', 'icon': 'FileText',
                           'feature_flag': '', 'permission_flag': '', 'badge_source': '', 'priority': 7,
                           'discovery_hint': '', 'nudge_trigger': ''},
                          {'id': 'settings', 'label': 'Settings', 'route': '/settings', 'icon': 'Settings',
                           'feature_flag': '', 'permission_flag': 'can_manage_settings', 'badge_source': '',
                           'priority': 8, 'discovery_hint': '', 'nudge_trigger': ''},
                          {'id': 'levies', 'label': 'Levy management', 'route': '/financials/levy-payments',
                           'icon': 'CreditCard', 'feature_flag': '', 'permission_flag': '', 'badge_source': '',
                           'priority': 9, 'discovery_hint': '', 'nudge_trigger': ''},
                          {'id': 'meetings', 'label': 'Meetings', 'route': '/governance/meetings', 'icon': 'Calendar',
                           'feature_flag': '', 'permission_flag': '', 'badge_source': '', 'priority': 10,
                           'discovery_hint': '', 'nudge_trigger': ''},
                          {'id': 'bylaws', 'label': 'By-laws', 'route': '/governance/bylaws', 'icon': 'BookOpen',
                           'feature_flag': '', 'permission_flag': '', 'badge_source': '', 'priority': 11,
                           'discovery_hint': '', 'nudge_trigger': ''},
                          {'id': 'documents', 'label': 'Documents', 'route': '/documents',
                           'icon': 'FolderOpen', 'feature_flag': '', 'permission_flag': '', 'badge_source': '',
                           'priority': 12, 'discovery_hint': '', 'nudge_trigger': ''},
                          {'id': 'insurance', 'label': 'Insurance', 'route': '/insurance', 'icon': 'Shield',
                           'feature_flag': '', 'permission_flag': '', 'badge_source': '', 'priority': 13,
                           'discovery_hint': '', 'nudge_trigger': ''}],
                       'created_at': '2026-04-01T05:45:53.074005+00:00', 'id': 'nav-strata_manager', 'simple_items': [
                          {'id': 'dashboard', 'label': 'Dashboard', 'route': '/dashboard', 'icon': 'LayoutDashboard',
                           'feature_flag': '', 'permission_flag': '', 'badge_source': 'sla_breached', 'priority': 1},
                          {'id': 'requests', 'label': 'Requests', 'route': '/requests/new',
                           'icon': 'MessageSquare', 'feature_flag': 'smart_requests', 'permission_flag': '',
                           'badge_source': 'requests_overdue', 'priority': 2},
                          {'id': 'finance', 'label': 'Finance', 'route': '/financials', 'icon': 'DollarSign',
                           'feature_flag': '', 'permission_flag': '', 'badge_source': '', 'priority': 3},
                          {'id': 'maintenance', 'label': 'Maintenance', 'route': '/maintenance',
                           'icon': 'Wrench', 'feature_flag': '', 'permission_flag': '',
                           'badge_source': 'approvals_pending', 'priority': 4},
                          {'id': 'compliance', 'label': 'Compliance', 'route': '/compliance',
                           'icon': 'ShieldCheck', 'feature_flag': '', 'permission_flag': '',
                           'badge_source': 'compliance_overdue', 'priority': 5}],
                       'updated_at': '2026-04-01T10:21:42.315393+00:00', 'version': 1}, {'role': 'super_admin',
                                                                                         'advanced_items': [
                                                                                             {'id': 'requests',
                                                                                              'label': 'Requests',
                                                                                              'route': '/requests/new',
                                                                                              'icon': 'MessageSquare',
                                                                                              'feature_flag': 'smart_requests',
                                                                                              'permission_flag': '',
                                                                                              'badge_source': 'requests_overdue',
                                                                                              'priority': 1,
                                                                                              'discovery_hint': 'All maintenance & change requests',
                                                                                              'nudge_trigger': 'open_requests_gte_5'},
                                                                                             {'id': 'approvals',
                                                                                              'label': 'Approvals',
                                                                                              'route': '/requests/my-approvals',
                                                                                              'icon': 'CheckSquare',
                                                                                              'feature_flag': '',
                                                                                              'permission_flag': '',
                                                                                              'badge_source': 'approvals_pending',
                                                                                              'priority': 2,
                                                                                              'discovery_hint': '',
                                                                                              'nudge_trigger': ''},
                                                                                             {'id': 'compliance',
                                                                                              'label': 'Compliance',
                                                                                              'route': '/compliance',
                                                                                              'icon': 'ShieldCheck',
                                                                                              'feature_flag': '',
                                                                                              'permission_flag': '',
                                                                                              'badge_source': 'compliance_overdue',
                                                                                              'priority': 3,
                                                                                              'discovery_hint': '',
                                                                                              'nudge_trigger': ''},
                                                                                             {'id': 'reports',
                                                                                              'label': 'Reports',
                                                                                              'route': '/reports',
                                                                                              'icon': 'FileText',
                                                                                              'feature_flag': '',
                                                                                              'permission_flag': '',
                                                                                              'badge_source': '',
                                                                                              'priority': 4,
                                                                                              'discovery_hint': '',
                                                                                              'nudge_trigger': ''},
                                                                                             {'id': 'meetings',
                                                                                              'label': 'Meetings',
                                                                                              'route': '/governance/meetings',
                                                                                              'icon': 'Calendar',
                                                                                              'feature_flag': '',
                                                                                              'permission_flag': '',
                                                                                              'badge_source': '',
                                                                                              'priority': 5,
                                                                                              'discovery_hint': '',
                                                                                              'nudge_trigger': ''},
                                                                                             {'id': 'bylaws',
                                                                                              'label': 'By-laws',
                                                                                              'route': '/governance/bylaws',
                                                                                              'icon': 'BookOpen',
                                                                                              'feature_flag': '',
                                                                                              'permission_flag': '',
                                                                                              'badge_source': '',
                                                                                              'priority': 6,
                                                                                              'discovery_hint': '',
                                                                                              'nudge_trigger': ''},
                                                                                             {'id': 'proposals',
                                                                                              'label': 'Proposals',
                                                                                              'route': '/governance/proposals',
                                                                                              'icon': 'Vote',
                                                                                              'feature_flag': '',
                                                                                              'permission_flag': '',
                                                                                              'badge_source': 'proposals_open_vote',
                                                                                              'priority': 7,
                                                                                              'discovery_hint': '',
                                                                                              'nudge_trigger': ''},
                                                                                             {'id': 'ec-members',
                                                                                              'label': 'EC members',
                                                                                              'route': '/governance/ec-members',
                                                                                              'icon': 'UserCheck',
                                                                                              'feature_flag': '',
                                                                                              'permission_flag': '',
                                                                                              'badge_source': '',
                                                                                              'priority': 8,
                                                                                              'discovery_hint': '',
                                                                                              'nudge_trigger': ''},
                                                                                             {'id': 'notices',
                                                                                              'label': 'Notices',
                                                                                              'route': '/community/notices',
                                                                                              'icon': 'Bell',
                                                                                              'feature_flag': '',
                                                                                              'permission_flag': '',
                                                                                              'badge_source': 'notices_unread',
                                                                                              'priority': 9,
                                                                                              'discovery_hint': '',
                                                                                              'nudge_trigger': ''},
                                                                                             {'id': 'community',
                                                                                              'label': 'Community',
                                                                                              'route': '/community',
                                                                                              'icon': 'Users',
                                                                                              'feature_flag': '',
                                                                                              'permission_flag': '',
                                                                                              'badge_source': '',
                                                                                              'priority': 10,
                                                                                              'discovery_hint': '',
                                                                                              'nudge_trigger': ''},
                                                                                             {'id': 'events',
                                                                                              'label': 'Events',
                                                                                              'route': '/community/events',
                                                                                              'icon': 'Calendar',
                                                                                              'feature_flag': '',
                                                                                              'permission_flag': '',
                                                                                              'badge_source': '',
                                                                                              'priority': 11,
                                                                                              'discovery_hint': '',
                                                                                              'nudge_trigger': ''},
                                                                                             {'id': 'marketplace',
                                                                                              'label': 'Marketplace',
                                                                                              'route': '/community/marketplace',
                                                                                              'icon': 'ShoppingBag',
                                                                                              'feature_flag': '',
                                                                                              'permission_flag': '',
                                                                                              'badge_source': '',
                                                                                              'priority': 12,
                                                                                              'discovery_hint': '',
                                                                                              'nudge_trigger': ''},
                                                                                             {'id': 'documents',
                                                                                              'label': 'Documents',
                                                                                              'route': '/documents',
                                                                                              'icon': 'FolderOpen',
                                                                                              'feature_flag': '',
                                                                                              'permission_flag': '',
                                                                                              'badge_source': '',
                                                                                              'priority': 13,
                                                                                              'discovery_hint': '',
                                                                                              'nudge_trigger': ''},
                                                                                             {'id': 'levies',
                                                                                              'label': 'Levy management',
                                                                                              'route': '/financials/levy-payments',
                                                                                              'icon': 'CreditCard',
                                                                                              'feature_flag': '',
                                                                                              'permission_flag': '',
                                                                                              'badge_source': 'levy_due_soon',
                                                                                              'priority': 14,
                                                                                              'discovery_hint': '',
                                                                                              'nudge_trigger': ''},
                                                                                             {'id': 'insurance',
                                                                                              'label': 'Insurance',
                                                                                              'route': '/insurance',
                                                                                              'icon': 'Shield',
                                                                                              'feature_flag': '',
                                                                                              'permission_flag': '',
                                                                                              'badge_source': '',
                                                                                              'priority': 15,
                                                                                              'discovery_hint': '',
                                                                                              'nudge_trigger': ''},
                                                                                             {'id': 'settings',
                                                                                              'label': 'Settings',
                                                                                              'route': '/settings',
                                                                                              'icon': 'Settings',
                                                                                              'feature_flag': '',
                                                                                              'permission_flag': 'can_manage_settings',
                                                                                              'badge_source': '',
                                                                                              'priority': 16,
                                                                                              'discovery_hint': '',
                                                                                              'nudge_trigger': ''},
                                                                                             {'id': 'feature-toggles',
                                                                                              'label': 'Feature toggles',
                                                                                              'route': '/admin/feature-toggles',
                                                                                              'icon': 'ToggleLeft',
                                                                                              'feature_flag': '',
                                                                                              'permission_flag': 'can_manage_settings',
                                                                                              'badge_source': '',
                                                                                              'priority': 17,
                                                                                              'discovery_hint': '',
                                                                                              'nudge_trigger': ''},
                                                                                             {'id': 'audit-logs',
                                                                                              'label': 'Audit logs',
                                                                                              'route': '/admin/audit-logs',
                                                                                              'icon': 'FileText',
                                                                                              'feature_flag': '',
                                                                                              'permission_flag': 'can_view_audit',
                                                                                              'badge_source': '',
                                                                                              'priority': 18,
                                                                                              'discovery_hint': '',
                                                                                              'nudge_trigger': ''},
                                                                                             {'id': 'portfolio',
                                                                                              'label': 'Portfolio',
                                                                                              'route': '/management/portfolio',
                                                                                              'icon': 'Building2',
                                                                                              'feature_flag': 'portfolio_dashboard',
                                                                                              'permission_flag': '',
                                                                                              'badge_source': '',
                                                                                             'priority': 19,
                                                                                             'discovery_hint': 'All buildings in one view',
                                                                                             'nudge_trigger': 'multiple_buildings_accessible'},
                                                                                             {'id': 'building-onboarding',
                                                                                              'label': 'Onboard Building',
                                                                                              'route': '/admin/portfolio/onboard',
                                                                                              'icon': 'ClipboardCheck',
                                                                                              'feature_flag': 'building_onboarding',
                                                                                              'permission_flag': '',
                                                                                              'badge_source': '',
                                                                                             'priority': 20,
                                                                                             'discovery_hint': 'Run the full scheme onboarding workflow',
                                                                                             'nudge_trigger': ''},
                                                                                             {'id': 'quick-building-setup',
                                                                                              'label': 'Quick Building Setup',
                                                                                              'route': '/admin/buildings/onboard',
                                                                                              'icon': 'Building2',
                                                                                             'feature_flag': 'building_onboarding',
                                                                                             'permission_flag': '',
                                                                                             'badge_source': '',
                                                                                             'priority': 21,
                                                                                             'discovery_hint': 'Create a scheme shell and import a Strata Roll CSV',
                                                                                             'nudge_trigger': ''},
                                                                                             {'id': 'financial-onboarding',
                                                                                              'label': 'Financial Onboarding',
                                                                                              'route': '/admin/financial-onboarding',
                                                                                              'icon': 'Upload',
                                                                                              'feature_flag': 'historical_financial_reconstruction',
                                                                                              'permission_flag': 'can_manage_finances',
                                                                                              'badge_source': '',
                                                                                              'priority': 22,
                                                                                              'discovery_hint': 'Complete historical financial onboarding through Demo Bank staging',
                                                                                              'nudge_trigger': ''},
                                                                                             {'id': 'workflows',
                                                                                              'label': 'Workflows',
                                                                                              'route': '/admin/workflows',
                                                                                              'icon': 'GitBranch',
                                                                                              'feature_flag': 'workflow_governance',
                                                                                              'permission_flag': '',
                                                                                              'badge_source': '',
                                                                                              'priority': 23,
                                                                                              'discovery_hint': 'See which automations ran today',
                                                                                              'nudge_trigger': ''}],
                                                                                         'created_at': '2026-04-01T05:45:53.074005+00:00',
                                                                                         'id': 'nav-super_admin',
                                                                                         'simple_items': [
                                                                                             {'id': 'dashboard',
                                                                                              'label': 'Dashboard',
                                                                                              'route': '/dashboard',
                                                                                              'icon': 'LayoutDashboard',
                                                                                              'feature_flag': '',
                                                                                              'permission_flag': '',
                                                                                              'badge_source': '',
                                                                                              'priority': 1},
                                                                                             {'id': 'users',
                                                                                              'label': 'Users',
                                                                                              'route': '/admin/users',
                                                                                              'icon': 'Users',
                                                                                              'feature_flag': '',
                                                                                              'permission_flag': 'can_manage_users',
                                                                                              'badge_source': '',
                                                                                              'priority': 2},
                                                                                             {'id': 'finance',
                                                                                              'label': 'Finance',
                                                                                              'route': '/financials',
                                                                                              'icon': 'DollarSign',
                                                                                              'feature_flag': '',
                                                                                              'permission_flag': '',
                                                                                              'badge_source': '',
                                                                                              'priority': 3},
                                                                                             {'id': 'maintenance',
                                                                                              'label': 'Maintenance',
                                                                                              'route': '/maintenance',
                                                                                              'icon': 'Wrench',
                                                                                              'feature_flag': '',
                                                                                              'permission_flag': '',
                                                                                              'badge_source': 'approvals_pending',
                                                                                              'priority': 4},
                                                                                             {'id': 'system',
                                                                                              'label': 'System',
                                                                                              'route': '/admin',
                                                                                              'icon': 'Settings',
                                                                                              'feature_flag': '',
                                                                                              'permission_flag': 'can_manage_settings',
                                                                                              'badge_source': '',
                                                                                              'priority': 5}],
                                                                                         'updated_at': '2026-04-01T10:21:42.315393+00:00',
                                                                                         'version': 1},
                      {'role': 'tenant', 'advanced_items': [
                          {'id': 'events', 'label': 'Events', 'route': '/community/events', 'icon': 'Calendar',
                           'feature_flag': '', 'permission_flag': '', 'badge_source': '', 'priority': 1,
                           'discovery_hint': '', 'nudge_trigger': ''},
                          {'id': 'marketplace', 'label': 'Marketplace', 'route': '/community/marketplace',
                           'icon': 'ShoppingBag', 'feature_flag': '', 'permission_flag': '', 'badge_source': '',
                           'priority': 2, 'discovery_hint': '', 'nudge_trigger': ''},
                          {'id': 'bookings', 'label': 'Bookings', 'route': '/community/bookings', 'icon': 'BookMarked',
                           'feature_flag': '', 'permission_flag': '', 'badge_source': '', 'priority': 3,
                           'discovery_hint': '', 'nudge_trigger': ''},
                          {'id': 'volunteer-credits', 'label': 'Volunteer credits', 'route': '/community/volunteer',
                           'icon': 'Star', 'feature_flag': 'volunteer_credits', 'permission_flag': '',
                           'badge_source': '', 'priority': 4, 'discovery_hint': 'Earn levy credits for helping out',
                           'nudge_trigger': ''},
                          {'id': 'tenancy-passport', 'label': 'My passport', 'route': '/profile/passport',
                           'icon': 'IdCard', 'feature_flag': 'tenancy_passport', 'permission_flag': '',
                           'badge_source': '', 'priority': 5, 'discovery_hint': 'Your portable residency record',
                           'nudge_trigger': ''},
                          {'id': 'suburb-radar', 'label': 'Suburb radar', 'route': '/intelligence/suburb-radar',
                           'icon': 'Map', 'feature_flag': 'suburb_radar', 'permission_flag': '', 'badge_source': '',
                           'priority': 6, 'discovery_hint': 'Weekly local intelligence', 'nudge_trigger': ''},
                          {'id': 'bylaws', 'label': 'By-laws', 'route': '/governance/bylaws', 'icon': 'BookOpen',
                           'feature_flag': '', 'permission_flag': '', 'badge_source': '', 'priority': 7,
                           'discovery_hint': '', 'nudge_trigger': ''},
                          {'id': 'documents', 'label': 'Documents', 'route': '/documents',
                           'icon': 'FolderOpen', 'feature_flag': '', 'permission_flag': '', 'badge_source': '',
                           'priority': 8, 'discovery_hint': '', 'nudge_trigger': ''}],
                       'created_at': '2026-04-01T05:45:53.074005+00:00', 'id': 'nav-tenant', 'simple_items': [
                          {'id': 'home', 'label': 'Home', 'route': '/dashboard', 'icon': 'Home', 'feature_flag': '',
                           'permission_flag': '', 'badge_source': '', 'priority': 1},
                          {'id': 'requests', 'label': 'Requests', 'route': '/requests/new',
                           'icon': 'MessageSquare', 'feature_flag': 'smart_requests', 'permission_flag': '',
                           'badge_source': 'requests_new', 'priority': 2},
                          {'id': 'notices', 'label': 'Notices', 'route': '/community/notices', 'icon': 'Bell',
                           'feature_flag': '', 'permission_flag': '', 'badge_source': 'notices_unread', 'priority': 3},
                          {'id': 'parcels', 'label': 'Parcels', 'route': '/community/parcels', 'icon': 'Package',
                           'feature_flag': '', 'permission_flag': '', 'badge_source': 'parcels_waiting', 'priority': 4},
                          {'id': 'chat', 'label': 'Chat', 'route': '/community/chat', 'icon': 'MessageCircle',
                           'feature_flag': '', 'permission_flag': '', 'badge_source': '', 'priority': 5}],
                       'updated_at': '2026-04-01T10:21:42.315393+00:00', 'version': 1}]


async def seed_navigation_configs():
    """Upsert all navigation_configs entries. Safe to re-run."""
    client = AsyncMongoClient(os.environ['MONGO_URL'])
    db = client[os.environ['DB_NAME']]
    cleanup = await db.navigation_configs.delete_many({"role": {"$in": list(LEGACY_NAV_ROLES)}})
    if cleanup.deleted_count:
        print(f'navigation_configs: removed {cleanup.deleted_count} legacy role configs')
    upserted = 0
    for entry in NAVIGATION_CONFIGS:
        result = await db.navigation_configs.update_one(
            {'role': entry['role']},
            {'$set': entry, '$setOnInsert': {'created_at': entry.get('created_at', entry.get('updated_at', ''))}},
            upsert=True
        )
        if result.upserted_id or result.modified_count:
            upserted += 1
    print(f'navigation_configs: {upserted} upserted ({len(NAVIGATION_CONFIGS)} total)')
    await client.close()


if __name__ == "__main__":
    asyncio.run(seed_navigation_configs())
