"""
Feature toggles — global defaults + per-building overrides.
Building 13195 = East Gate Residences.

Generated from live DB on 2026-04-01. DO NOT EDIT MANUALLY.
Regenerate with:  cd backend && venv/bin/python3 ../scripts/db/snapshot_all.py
"""
import asyncio
import os
from pathlib import Path

from dotenv import load_dotenv
from pymongo import AsyncMongoClient

ROOT_DIR = Path(__file__).parent.parent
load_dotenv(ROOT_DIR / ".env")

FEATURE_TOGGLES = [{'feature_key': 'announcements', 'feature_name': 'Legacy Announcements API',
                    'description': 'Compatibility flag for legacy announcement API reads while notices are the canonical UI',
                    'is_enabled': True,
                    'category': 'communication', 'icon': 'Megaphone', 'routes': [],
                    'created_at': datetime.datetime(2026, 2, 14, 13, 22, 26, 439000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000),
                    'updated_by': 'f26f3caf-710f-4a61-84b1-26d8bcac7042', 'building_id': None, 'depends_on': []},
                   {'feature_key': 'blog_management', 'feature_name': 'Blog Management',
                    'description': 'Create and manage community news and blog posts', 'is_enabled': True,
                    'category': 'communication', 'icon': 'Newspaper',
                    'routes': ['/community/blog-management'],
                    'created_at': datetime.datetime(2026, 2, 23, 23, 9, 31, 977000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000), 'updated_by': None,
                    'building_id': None, 'depends_on': ['news']},
                   {'feature_key': 'chat', 'feature_name': 'Community Chat',
                    'description': 'Group chat and community discussions', 'is_enabled': True,
                    'category': 'communication', 'icon': 'MessageCircle', 'routes': ['/community/chat'],
                    'created_at': datetime.datetime(2026, 2, 14, 13, 22, 26, 439000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000), 'updated_by': None,
                    'building_id': None, 'depends_on': []},
                   {'feature_key': 'email', 'feature_name': 'Custom Email Domain',
                    'description': 'Email addresses with @eastgateresidences.com.au domain', 'is_enabled': True,
                    'category': 'communication', 'icon': 'AtSign', 'routes': [],
                    'created_at': datetime.datetime(2026, 2, 14, 13, 22, 26, 439000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000),
                    'updated_by': 'f26f3caf-710f-4a61-84b1-26d8bcac7042', 'building_id': None, 'depends_on': []},
                   {'feature_key': 'email_preferences', 'feature_name': 'Email Preferences',
                    'description': 'Manage email notification preferences', 'is_enabled': True,
                    'category': 'communication', 'icon': 'Bell', 'routes': ['/my-communications'],
                    'created_at': datetime.datetime(2026, 2, 16, 2, 31, 16, 322000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000), 'updated_by': None,
                    'building_id': None, 'depends_on': ['email']},
                   {'feature_key': 'manual_email', 'feature_name': 'Manual Email Communication',
                    'description': 'Send manual email communications to individual residents, owners or community groups',
                    'is_enabled': True, 'category': 'communication', 'icon': 'MailOpen',
                    'routes': ['/admin/communications'],
                    'created_at': datetime.datetime(2026, 3, 6, 12, 4, 33, 239000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000), 'updated_by': None,
                    'building_id': None, 'depends_on': ['email']},
                   {'feature_key': 'news', 'feature_name': 'News & Blog', 'description': 'Community news and updates',
                    'is_enabled': True, 'category': 'communication', 'icon': 'Newspaper', 'routes': ['/blog'],
                    'created_at': datetime.datetime(2026, 2, 14, 13, 22, 26, 439000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000),
                    'updated_by': 'f26f3caf-710f-4a61-84b1-26d8bcac7042', 'building_id': None, 'depends_on': []},
                   {'feature_key': 'notices', 'feature_name': 'Notice Board',
                    'description': 'Official notices with acknowledgment tracking and community discussions',
                    'is_enabled': True, 'category': 'communication', 'icon': 'Bell', 'routes': ['/community/notices'],
                    'created_at': datetime.datetime(2026, 2, 14, 13, 22, 26, 439000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000),
                    'updated_by': 'f26f3caf-710f-4a61-84b1-26d8bcac7042', 'building_id': None,
                    'depends_on': []},
                   {'feature_key': 'notifications_management', 'feature_name': 'Notification Management',
                    'description': 'Admin notification system management', 'is_enabled': True,
                    'category': 'communication', 'icon': 'Send', 'routes': ['/notifications'],
                    'created_at': datetime.datetime(2026, 2, 16, 2, 31, 16, 322000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000), 'updated_by': None,
                    'building_id': None, 'depends_on': []},
                   {'feature_key': 'private_messages', 'feature_name': 'Private Messages',
                    'description': 'Direct messaging between residents', 'is_enabled': True,
                    'category': 'communication', 'icon': 'Mail', 'routes': ['/community/messages'],
                    'created_at': datetime.datetime(2026, 2, 14, 13, 22, 26, 439000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000), 'updated_by': None,
                    'building_id': None, 'depends_on': ['chat']},
                   {'feature_key': 'webmail', 'feature_name': 'Email Access',
                    'description': 'Access East Gate Mail webmail client', 'is_enabled': True,
                    'category': 'communication', 'icon': 'AtSign', 'routes': ['/my-communications'],
                    'created_at': datetime.datetime(2026, 2, 16, 2, 31, 16, 322000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000),
                    'updated_by': 'f26f3caf-710f-4a61-84b1-26d8bcac7042', 'building_id': None, 'depends_on': ['email']},
                   {'feature_key': 'building_health_score', 'feature_name': 'Building Health Score',
                    'description': 'Computed building health dashboard and score', 'is_enabled': True,
                    'category': 'community', 'icon': 'HeartPulse', 'routes': ['/community-dashboard'],
                    'depends_on': [], 'building_id': None,
                    'created_at': datetime.datetime(2026, 3, 31, 1, 28, 49, 481000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000), 'updated_by': None},
                   {'feature_key': 'directory', 'feature_name': 'Resident Directory',
                    'description': 'Browse resident profiles and contact information', 'is_enabled': True,
                    'category': 'community', 'icon': 'Users', 'routes': ['/community/directory'],
                    'created_at': datetime.datetime(2026, 2, 14, 13, 22, 26, 439000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000), 'updated_by': None,
                    'building_id': None, 'depends_on': []}, {'feature_key': 'events', 'feature_name': 'Events Calendar',
                                                             'description': 'View and manage community events',
                                                             'is_enabled': True, 'category': 'community',
                                                             'icon': 'CalendarDays', 'routes': ['/community/events'],
                                                             'created_at': datetime.datetime(2026, 2, 14, 13, 22, 26,
                                                                                             439000),
                                                             'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48,
                                                                                             513000),
                                                             'updated_by': None, 'building_id': None, 'depends_on': []},
                   {'feature_key': 'group_buying', 'feature_name': 'Community Group Buying',
                    'description': 'Bulk purchase campaigns for community savings', 'is_enabled': True,
                    'category': 'community', 'icon': 'ShoppingBag', 'routes': ['/community/group-buy'],
                    'depends_on': [], 'building_id': None, 'created_at': datetime.datetime(2026, 4, 1, 0, 5, 3, 926000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000), 'updated_by': None},
                   {'feature_key': 'marketplace', 'feature_name': 'Marketplace',
                    'description': 'Buy, sell, and trade within the community', 'is_enabled': True,
                    'category': 'community', 'icon': 'ShoppingCart',
                    'routes': ['/community/marketplace', '/community/my-listings'],
                    'created_at': datetime.datetime(2026, 2, 14, 13, 22, 26, 439000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000), 'updated_by': None,
                    'building_id': None, 'depends_on': []},
                   {'feature_key': 'pet_register', 'feature_name': 'Pet Register',
                    'description': 'Register and manage pets living in the complex with owner unit tracking and approval status',
                    'is_enabled': True, 'category': 'community', 'icon': 'PawPrint',
                    'routes': ['/community/pet-register'],
                    'created_at': datetime.datetime(2026, 3, 6, 12, 4, 33, 239000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000),
                    'updated_by': 'f26f3caf-710f-4a61-84b1-26d8bcac7042', 'building_id': None, 'depends_on': []},
                   {'feature_key': 'smart_requests', 'feature_name': 'Smart Request Triage',
                    'description': 'AI-assisted workflow request triage and routing', 'is_enabled': True,
                    'category': 'community', 'icon': 'Zap', 'routes': ['/requests/new'],
                    'depends_on': [], 'building_id': None,
                    'created_at': datetime.datetime(2026, 3, 31, 1, 28, 49, 481000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000), 'updated_by': None},
                   {'feature_key': 'tenancy_passport', 'feature_name': 'Tenancy Passport',
                    'description': 'Portable residency score and PDF passport for tenants', 'is_enabled': True,
                    'category': 'community', 'icon': 'FileCheck', 'routes': ['/profile/passport'],
                    'depends_on': [], 'building_id': None, 'created_at': datetime.datetime(2026, 4, 1, 0, 5, 3, 926000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000), 'updated_by': None},
                   {'feature_key': 'volunteer', 'feature_name': 'Volunteer Events',
                    'description': 'Coordinate volunteer events and apply levy credits', 'is_enabled': True,
                    'category': 'community', 'icon': 'HandHelping', 'routes': ['/community/volunteer'],
                    'depends_on': [], 'building_id': None,
                    'created_at': datetime.datetime(2026, 3, 31, 1, 28, 49, 481000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000), 'updated_by': None},
                   {'feature_key': 'volunteer_credits', 'feature_name': 'Volunteer Levy Credits',
                    'description': 'Volunteer credit system — earn levy credits through community contributions',
                    'is_enabled': True, 'category': 'community', 'icon': 'Heart', 'routes': [], 'depends_on': [],
                    'building_id': None, 'created_at': datetime.datetime(2026, 4, 1, 0, 5, 3, 926000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000), 'updated_by': None},
                   {'feature_key': 'documents', 'feature_name': 'Documents Management',
                    'description': 'Upload, view, and manage community documents', 'is_enabled': True,
                    'category': 'core', 'icon': 'FileText', 'routes': ['/documents'],
                    'created_at': datetime.datetime(2026, 2, 14, 13, 22, 26, 439000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000),
                    'updated_by': 'f26f3caf-710f-4a61-84b1-26d8bcac7042', 'building_id': None, 'depends_on': []},
                   {'feature_key': 'sidebar', 'feature_name': 'Sidebar',
                    'description': 'Redesigned grouped and collapsible sidebar navigation', 'is_enabled': True,
                    'category': 'core', 'icon': 'Layout', 'routes': [],
                    'created_at': datetime.datetime(2026, 2, 23, 23, 9, 31, 977000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000), 'updated_by': None,
                    'building_id': None, 'depends_on': []}, {'feature_key': 'user_guide', 'feature_name': 'User Guide',
                                                             'description': 'Access to user guide documentation',
                                                             'is_enabled': True, 'category': 'core', 'icon': 'BookOpen',
                                                             'routes': ['/user-guides/index.html'],
                                                             'created_at': datetime.datetime(2026, 2, 16, 2, 31, 16,
                                                                                             322000),
                                                             'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48,
                                                                                             513000),
                                                             'updated_by': None, 'building_id': None, 'depends_on': []},
                   {'feature_key': 'building_pulse', 'feature_name': 'Building Pulse',
                    'description': 'Live activity feed showing recent building events', 'is_enabled': True,
                    'category': 'engagement', 'icon': 'Activity', 'routes': [], 'depends_on': [], 'building_id': None,
                    'created_at': datetime.datetime(2026, 4, 1, 0, 5, 3, 926000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000), 'updated_by': None},
                   {'feature_key': 'morning_card', 'feature_name': 'Morning Card',
                    'description': 'Single most relevant action card shown on dashboard load', 'is_enabled': True,
                    'category': 'engagement', 'icon': 'Zap', 'routes': [], 'depends_on': [], 'building_id': None,
                    'created_at': datetime.datetime(2026, 4, 1, 0, 5, 3, 926000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000), 'updated_by': None},
                   {'feature_key': 'bookings', 'feature_name': 'Facility Bookings',
                    'description': 'Book common areas and amenities', 'is_enabled': True, 'category': 'facilities',
                    'icon': 'CalendarCheck', 'routes': ['/community/bookings'],
                    'created_at': datetime.datetime(2026, 2, 14, 13, 22, 26, 439000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000),
                    'updated_by': 'f26f3caf-710f-4a61-84b1-26d8bcac7042', 'building_id': None, 'depends_on': []},
                   {'feature_key': 'defects', 'feature_name': 'Defect Reports',
                    'description': 'Report and track building defects', 'is_enabled': True, 'category': 'facilities',
                    'icon': 'AlertCircle', 'routes': ['/maintenance/defects'],
                    'created_at': datetime.datetime(2026, 2, 14, 13, 22, 26, 439000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000),
                    'updated_by': 'f26f3caf-710f-4a61-84b1-26d8bcac7042', 'building_id': None,
                    'depends_on': ['maintenance']},
                   {'feature_key': 'maintenance', 'feature_name': 'Maintenance Requests',
                    'description': 'Submit and track maintenance requests', 'is_enabled': True,
                    'category': 'facilities', 'icon': 'Wrench', 'routes': ['/maintenance'],
                    'created_at': datetime.datetime(2026, 2, 14, 13, 22, 26, 439000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000),
                    'updated_by': 'f26f3caf-710f-4a61-84b1-26d8bcac7042', 'building_id': None, 'depends_on': []},
                   {'feature_key': 'parcels', 'feature_name': 'Parcel Management',
                    'description': 'Track parcel deliveries and collections', 'is_enabled': True,
                    'category': 'facilities', 'icon': 'Package', 'routes': ['/community/parcels'],
                    'created_at': datetime.datetime(2026, 2, 14, 13, 22, 26, 439000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000),
                    'updated_by': 'f26f3caf-710f-4a61-84b1-26d8bcac7042', 'building_id': None, 'depends_on': []},
                   {'feature_key': 'ppm_schedule', 'feature_name': 'Preventive Maintenance Plan (PPM)',
                    'description': "79-item compliance calendar sourced from the building's PPM schedule — section/status/compliance filters, completion logging with auto-recomputed next due dates, and daily manager/resident email notifications at 30/14/7/0-day thresholds",
                    'is_enabled': True, 'category': 'facilities', 'icon': 'Calendar',
                    'routes': ['/maintenance'], 'depends_on': ['maintenance'], 'building_id': None,
                    'created_at': datetime.datetime(2026, 3, 31, 8, 20, 12, 382000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000), 'updated_by': None},
                   {'feature_key': 'requests', 'feature_name': 'Request System',
                    'description': 'Submit general requests to management', 'is_enabled': True,
                    'category': 'facilities', 'icon': 'FileQuestion', 'routes': ['/requests'],
                    'created_at': datetime.datetime(2026, 2, 16, 2, 31, 16, 322000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000),
                    'updated_by': 'f26f3caf-710f-4a61-84b1-26d8bcac7042', 'building_id': None, 'depends_on': []},
                   {'feature_key': 'schedule', 'feature_name': 'Schedule Management',
                    'description': 'Service provider schedules and calendar', 'is_enabled': True,
                    'category': 'facilities', 'icon': 'Clock', 'routes': ['/maintenance/schedule'],
                    'created_at': datetime.datetime(2026, 2, 16, 2, 31, 16, 322000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000),
                    'updated_by': 'f26f3caf-710f-4a61-84b1-26d8bcac7042', 'building_id': None, 'depends_on': []},
                   {'feature_key': 'work_orders', 'feature_name': 'Work Orders',
                    'description': 'Full lifecycle management of work orders, quotes, vendor assignments, and invoice approvals',
                    'is_enabled': True, 'category': 'facilities', 'icon': 'Wrench',
                    'routes': ['/maintenance'],
                    'created_at': datetime.datetime(2026, 3, 4, 12, 17, 56, 937000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000),
                    'updated_by': 'f26f3caf-710f-4a61-84b1-26d8bcac7042', 'building_id': None,
                    'depends_on': ['maintenance']}, {'feature_key': 'approvals', 'feature_name': 'My Approvals',
                                                     'description': 'Invoice and payment approval queue',
                                                     'is_enabled': True, 'category': 'financial',
                                                     'icon': 'ClipboardCheck', 'routes': ['/requests/my-approvals'],
                                                     'created_at': datetime.datetime(2026, 2, 16, 2, 31, 16, 322000),
                                                     'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000),
                                                     'updated_by': 'f26f3caf-710f-4a61-84b1-26d8bcac7042',
                                                     'building_id': None, 'depends_on': ['finance']},
                   {'feature_key': 'arrears_recovery', 'feature_name': 'Debt Recovery Board',
                    'description': 'Overdue levy tracking, arrears recovery board, payment notices and per-unit debt analysis',
                    'is_enabled': True, 'category': 'financial', 'icon': 'TrendingDown',
                    'routes': ['/financials/arrears'], 'created_at': datetime.datetime(2026, 3, 6, 12, 4, 33, 239000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000),
                    'updated_by': 'f26f3caf-710f-4a61-84b1-26d8bcac7042', 'building_id': None,
                    'depends_on': ['finance']}, {'feature_key': 'building_financial_stress',
                                                 'feature_name': 'Building Financial Stress Early Warning',
                                                 'description': 'Predictive special levy forecasting using Reserve Adequacy Ratio, capital works gap analysis, maintenance backlog and expense trends. Shows 10-year reserve timeline and unit-level cost impact.',
                                                 'is_enabled': True, 'category': 'financial', 'icon': 'AlertTriangle',
                                                 'routes': ['/intelligence/building-stress'],
                                                 'created_at': datetime.datetime(2026, 3, 12, 0, 59, 23, 634000),
                                                 'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000),
                                                 'updated_by': None, 'building_id': None,
                                                 'depends_on': ['finance_intelligence']},
                   {'feature_key': 'collection_rate', 'feature_name': 'Collection Rate Analysis',
                    'description': 'Detailed levy collection rate analytics with per-unit breakdown and trend charts',
                    'is_enabled': True, 'category': 'financial', 'icon': 'BarChart2',
                    'routes': ['/financials/collection-rate'],
                    'created_at': datetime.datetime(2026, 3, 6, 12, 4, 33, 239000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000), 'updated_by': None,
                    'building_id': None, 'depends_on': ['finance']},
                   {'feature_key': 'council_rates', 'feature_name': 'Utilities & Property Services',
                    'description': 'Council rates and property service billing information', 'is_enabled': True,
                    'category': 'financial', 'icon': 'Landmark', 'routes': ['/financials/council-rates'],
                    'created_at': datetime.datetime(2026, 2, 23, 23, 9, 31, 977000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000), 'updated_by': None,
                    'building_id': None, 'depends_on': ['finance']},
                   {'feature_key': 'finance', 'feature_name': 'Finance Management',
                    'description': 'View financial reports, budgets, and levy payments', 'is_enabled': True,
                    'category': 'financial', 'icon': 'DollarSign',
                    'routes': ['/financials', '/financials/levy-payments', '/financials/projections'],
                    'created_at': datetime.datetime(2026, 2, 14, 13, 22, 26, 439000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000), 'updated_by': None,
                    'building_id': None, 'depends_on': []},
                   {'feature_key': 'finance_intelligence', 'feature_name': 'Financial Intelligence Dashboard',
                    'description': 'AI-powered financial forecasting, anomaly detection, health scoring and levy simulation',
                    'is_enabled': True, 'category': 'financial', 'icon': 'Brain',
                    'routes': ['/financials/intelligence'],
                    'created_at': datetime.datetime(2026, 2, 23, 23, 9, 31, 977000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000), 'updated_by': None,
                    'building_id': None, 'depends_on': ['finance']},
                   {'feature_key': 'financial_data_import', 'feature_name': 'Financial Data Import',
                    'description': 'Import financial data from Excel, CSV and third-party sources into the system',
                    'is_enabled': True, 'category': 'financial', 'icon': 'Upload',
                    'routes': ['/admin/financial-data'],
                    'created_at': datetime.datetime(2026, 3, 6, 12, 4, 33, 239000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000), 'updated_by': None,
                    'building_id': None, 'depends_on': ['finance']},
                   {'feature_key': 'financial_projections', 'feature_name': 'Budget Projections',
                    'description': 'Forward-looking financial projections, levy simulations and budget planning scenarios',
                    'is_enabled': True, 'category': 'financial', 'icon': 'TrendingUp',
                    'routes': ['/financials/projections'],
                    'created_at': datetime.datetime(2026, 3, 6, 12, 4, 33, 239000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000),
                    'updated_by': 'f26f3caf-710f-4a61-84b1-26d8bcac7042', 'building_id': None,
                    'depends_on': ['finance']},
                   {'feature_key': 'financial_year_import', 'feature_name': 'Financial Year Import',
                    'description': 'Upload and import comprehensive financial year data via CSV (owner details, levy amounts, budget categories, per-unit levy status)',
                    'is_enabled': True, 'category': 'financial', 'icon': 'Upload',
                    'roles': ['super_admin', 'strata_manager', 'chairman', 'strata_admin'], 'is_premium': False,
                    'sort_order': 40,
                    'routes': ['/admin/financial-year-import'],
                    'created_at': datetime.datetime(2026, 3, 17, 11, 55, 25, 518000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000), 'updated_by': None,
                    'building_id': None, 'depends_on': ['finance']},
                   {'feature_key': 'insurance_claims', 'feature_name': 'Insurance Claims',
                    'description': 'Track and manage building insurance claims and settlements', 'is_enabled': True,
                    'category': 'financial', 'icon': 'ShieldCheck', 'routes': ['/insurance/claims'],
                    'created_at': datetime.datetime(2026, 3, 4, 12, 17, 56, 937000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000),
                    'updated_by': 'f26f3caf-710f-4a61-84b1-26d8bcac7042', 'building_id': None,
                    'depends_on': ['finance', 'maintenance']},
                   {'feature_key': 'insurance_lending_hooks', 'feature_name': 'Insurance & Lending Risk Signals',
                    'description': 'Phase 2 insurance risk signals and lending valuation signals for underwriters and lenders. Includes risk tier classification and lender advisory notes.',
                    'is_enabled': True, 'category': 'financial', 'icon': 'Shield',
                    'roles': ['super_admin', 'chairman', 'strata_admin', 'strata_manager', 'ec_member'],
                    'routes': ['/insurance/lending'], 'depends_on': ['finance_intelligence'],
                    'building_id': None, 'created_at': datetime.datetime(2026, 3, 31, 1, 28, 49, 481000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000), 'updated_by': None},
                   {'feature_key': 'investor_dashboard', 'feature_name': 'Investor Intelligence Dashboard',
                    'description': 'Phase 2 investor-grade building and unit analysis: stress scores, TCO, levy trajectory, risk-adjusted yield, and investor grading (A–D).',
                    'is_enabled': True, 'category': 'financial', 'icon': 'TrendingUp',
                    'roles': ['super_admin', 'chairman', 'strata_admin', 'strata_manager', 'ec_member', 'owner'],
                    'routes': ['/investor'], 'depends_on': ['finance_intelligence'], 'building_id': None,
                    'created_at': datetime.datetime(2026, 3, 31, 1, 28, 49, 481000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000), 'updated_by': None},
                   {'feature_key': 'levy_fairness', 'feature_name': 'Levy Fairness Engine',
                    'description': 'Show the Levy Fairness analysis page to EC members, Chairman and Strata Manager (Super Admin always has access)',
                    'is_enabled': True, 'category': 'financial', 'icon': 'Scale',
                    'routes': ['/intelligence/levy-fairness'],
                    'created_at': datetime.datetime(2026, 3, 9, 3, 13, 32, 775000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000), 'updated_by': None,
                    'building_id': None, 'depends_on': ['finance']},
                   {'feature_key': 'levy_fairness_audit', 'feature_name': 'Levy Fairness — Audit Trail',
                    'description': 'View full audit log of model changes and group edits', 'is_enabled': True,
                    'category': 'financial', 'icon': 'Scale', 'roles': ['super_admin', 'strata_manager'],
                    'routes': ['/intelligence/levy-fairness'],
                    'created_at': datetime.datetime(2026, 3, 12, 0, 59, 23, 634000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000), 'updated_by': None,
                    'building_id': None, 'depends_on': ['levy_fairness']},
                   {'feature_key': 'levy_fairness_confidence', 'feature_name': 'Levy Fairness — Model Confidence Badge',
                    'description': 'Show data quality confidence score (High/Medium/Low) on the Overview tab',
                    'is_enabled': True, 'category': 'financial', 'icon': 'Scale',
                    'roles': ['super_admin', 'strata_manager', 'chairman', 'strata_admin', 'ec_member'],
                    'routes': ['/intelligence/levy-fairness'],
                    'created_at': datetime.datetime(2026, 3, 12, 0, 59, 23, 634000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000), 'updated_by': None,
                    'building_id': None, 'depends_on': ['levy_fairness']},
                   {'feature_key': 'levy_fairness_cross_subsidy',
                    'feature_name': 'Levy Fairness — Cross-Subsidy Report',
                    'description': 'Per-facility cross-subsidy table showing TH vs APT contributions',
                    'is_enabled': True, 'category': 'financial', 'icon': 'Scale',
                    'roles': ['super_admin', 'strata_manager', 'chairman', 'strata_admin', 'ec_member'],
                    'routes': ['/intelligence/levy-fairness'],
                    'created_at': datetime.datetime(2026, 3, 12, 0, 59, 23, 634000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000), 'updated_by': None,
                    'building_id': None, 'depends_on': ['levy_fairness']}, {'feature_key': 'levy_fairness_distribution',
                                                                            'feature_name': 'Levy Fairness — Distribution Histogram',
                                                                            'description': 'Before/after levy distribution histogram tab',
                                                                            'is_enabled': True, 'category': 'financial',
                                                                            'icon': 'Scale',
                                                                            'roles': ['super_admin', 'strata_manager',
                                                                                      'chairman', 'strata_admin',
                                                                                      'ec_member'],
                                                                            'routes': [
                                                                                '/intelligence/levy-fairness'],
                                                                            'created_at': datetime.datetime(2026, 3, 12,
                                                                                                            0, 59, 23,
                                                                                                            634000),
                                                                            'updated_at': datetime.datetime(2026, 4, 1,
                                                                                                            5, 45, 48,
                                                                                                            513000),
                                                                            'updated_by': None, 'building_id': None,
                                                                            'depends_on': ['levy_fairness']},
                   {'feature_key': 'levy_fairness_explain', 'feature_name': 'Levy Fairness — Explain This Result',
                    'description': 'Show per-unit explanation drawer with facility cost breakdown drivers',
                    'is_enabled': True, 'category': 'financial', 'icon': 'Scale',
                    'roles': ['super_admin', 'strata_manager', 'chairman', 'strata_admin', 'ec_member'],
                    'routes': ['/intelligence/levy-fairness'],
                    'created_at': datetime.datetime(2026, 3, 12, 0, 59, 23, 634000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000), 'updated_by': None,
                    'building_id': None, 'depends_on': ['levy_fairness']},
                   {'feature_key': 'levy_fairness_owner', 'feature_name': 'Levy Fairness — Owner View',
                    'description': 'Allow owners to view the read-only Levy Fairness page (they cannot edit groups or recompute)',
                    'is_enabled': True, 'category': 'financial', 'icon': 'Scale',
                    'routes': ['/intelligence/levy-fairness'],
                    'created_at': datetime.datetime(2026, 3, 9, 3, 13, 32, 775000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000),
                    'updated_by': 'f26f3caf-710f-4a61-84b1-26d8bcac7042', 'building_id': None,
                    'depends_on': ['levy_fairness']},
                   {'feature_key': 'levy_fairness_snapshots', 'feature_name': 'Levy Fairness — Lock Reference Scenario',
                    'description': 'Save and restore named model snapshots', 'is_enabled': True,
                    'category': 'financial', 'icon': 'Scale', 'roles': ['super_admin'],
                    'routes': ['/intelligence/levy-fairness'],
                    'created_at': datetime.datetime(2026, 3, 12, 0, 59, 23, 634000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000), 'updated_by': None,
                    'building_id': None, 'depends_on': ['levy_fairness']},
                   {'feature_key': 'levy_payments', 'feature_name': 'Levy Payment Portal',
                    'description': 'Owner levy payment submission, history, and management portal with verification workflow',
                    'is_enabled': True, 'category': 'financial', 'icon': 'CreditCard',
                    'routes': ['/financials/levy-payments'],
                    'created_at': datetime.datetime(2026, 3, 6, 12, 4, 33, 239000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000), 'updated_by': None,
                    'building_id': None, 'depends_on': ['finance']},
                   {'feature_key': 'my_finances', 'feature_name': 'My Finances Dashboard',
                    'description': 'Owner financial transparency dashboard — levy breakdown, savings, health',
                    'is_enabled': True, 'category': 'financial', 'icon': 'DollarSign',
                    'routes': ['/financials/my-finances'], 'depends_on': ['finance'], 'building_id': None,
                    'created_at': datetime.datetime(2026, 4, 1, 0, 5, 3, 926000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000), 'updated_by': None},
                   {'building_id': None, 'feature_key': 'owner_finance', 'category': 'financial',
                    'created_at': datetime.datetime(2026, 4, 1, 6, 48, 39, 131000),
                    'description': 'Personalised financial transparency dashboard for owners and tenants',
                    'feature_name': 'Owner Finance Dashboard', 'is_enabled': True,
                    'updated_at': datetime.datetime(2026, 4, 1, 6, 48, 39, 131000)},
                   {'feature_key': 'savings_ledger', 'feature_name': 'Savings Ledger',
                    'description': 'Track and record community cost savings events', 'is_enabled': True,
                    'category': 'financial', 'icon': 'PiggyBank', 'routes': ['/financials/savings'],
                    'depends_on': ['finance'], 'building_id': None,
                    'created_at': datetime.datetime(2026, 3, 31, 1, 28, 49, 481000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000), 'updated_by': None},
                   {'feature_key': 'spending_categories', 'feature_name': 'Spending Categories',
                    'description': 'Manage and configure budget spending categories for financial tracking and reporting',
                    'is_enabled': True, 'category': 'financial', 'icon': 'Tag',
                    'routes': ['/financials/spending-categories'],
                    'created_at': datetime.datetime(2026, 3, 6, 12, 4, 33, 239000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000), 'updated_by': None,
                    'building_id': None, 'depends_on': ['finance']},
                   {'feature_key': 'stress_score', 'feature_name': 'Building Financial Stress Score',
                    'description': 'Phase 2 seven-component stress score (0–100) with categories: healthy, watch, elevated, critical. Components: reserve adequacy, arrears, unreconciled exposure, maintenance pressure, liquidity, capital shock.',
                    'is_enabled': True, 'category': 'financial', 'icon': 'Activity',
                    'roles': ['super_admin', 'chairman', 'strata_admin', 'strata_manager', 'ec_member'],
                    'routes': ['/intelligence/building-stress'], 'depends_on': ['finance_intelligence'],
                    'building_id': None, 'created_at': datetime.datetime(2026, 3, 31, 1, 28, 49, 481000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000), 'updated_by': None},
                   {'feature_key': 'subsidy_map', 'feature_name': 'Levy Subsidy Map',
                    'description': 'Visualise cross-subsidy flows between lot groups (apartments, townhouses, etc.) based on levy payments vs benefit allocation.',
                    'is_enabled': True, 'category': 'financial', 'icon': 'Map',
                    'roles': ['super_admin', 'chairman', 'strata_admin', 'strata_manager', 'ec_member'],
                    'routes': ['/intelligence/levy-fairness'], 'depends_on': ['levy_fairness'], 'building_id': None,
                    'created_at': datetime.datetime(2026, 3, 31, 1, 28, 49, 481000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000), 'updated_by': None},
                   {'feature_key': 'water_bills', 'feature_name': 'Water Bills',
                    'description': 'Icon Water billing and usage tracking', 'is_enabled': True, 'category': 'financial',
                    'icon': 'Droplets', 'routes': ['/financials/water-bills'],
                    'created_at': datetime.datetime(2026, 2, 23, 23, 9, 31, 977000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000),
                    'updated_by': 'f26f3caf-710f-4a61-84b1-26d8bcac7042', 'building_id': None,
                    'depends_on': ['finance']}, {'feature_key': 'change_requests', 'feature_name': 'Change Requests',
                                                 'description': 'Review and approve user change requests',
                                                 'is_enabled': True, 'category': 'governance', 'icon': 'RefreshCw',
                                                 'routes': ['/admin/change-requests'],
                                                 'created_at': datetime.datetime(2026, 2, 16, 2, 31, 16, 322000),
                                                 'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000),
                                                 'updated_by': 'f26f3caf-710f-4a61-84b1-26d8bcac7042',
                                                 'building_id': None, 'depends_on': ['user_management']},
                   {'feature_key': 'compliance', 'feature_name': 'Compliance Checklist',
                    'description': 'Building compliance tracking and regulatory checklists', 'is_enabled': True,
                    'category': 'governance', 'icon': 'ClipboardCheck', 'routes': ['/compliance'],
                    'created_at': datetime.datetime(2026, 2, 23, 23, 9, 31, 977000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000), 'updated_by': None,
                    'building_id': None, 'depends_on': []},
                   {'feature_key': 'expired_accounts', 'feature_name': 'Expired Accounts',
                    'description': 'Manage expired user accounts', 'is_enabled': True, 'category': 'governance',
                    'icon': 'UserX', 'routes': ['/admin/expired-accounts'],
                    'created_at': datetime.datetime(2026, 2, 16, 2, 31, 16, 322000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000),
                    'updated_by': 'f26f3caf-710f-4a61-84b1-26d8bcac7042', 'building_id': None,
                    'depends_on': ['user_management']}, {'feature_key': 'meetings', 'feature_name': 'Meetings',
                                                         'description': 'Schedule and manage committee meetings',
                                                         'is_enabled': True, 'category': 'governance',
                                                         'icon': 'Calendar',
                                                         'routes': ['/governance/meetings', '/governance/agm-voting',
                                                                    '/governance/todos'],
                                                         'created_at': datetime.datetime(2026, 2, 14, 13, 22, 26,
                                                                                         439000),
                                                         'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000),
                                                         'updated_by': None, 'building_id': None, 'depends_on': []},
                   {'feature_key': 'owner_name_verification', 'feature_name': 'Owner Name Verification',
                    'description': 'Flag owner users whose registered name does not closely match the strata roll (primary or secondary owner). An amber warning triangle appears in User Management next to mismatched names, helping administrators detect potential fraud, data-entry errors or name changes.',
                    'is_enabled': True, 'category': 'governance', 'icon': 'AlertTriangle',
                    'roles': ['super_admin', 'strata_manager', 'chairman', 'strata_admin', 'ec_member'],
                    'routes': ['/admin/users'],
                    'created_at': datetime.datetime(2026, 3, 17, 11, 55, 25, 518000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000), 'updated_by': None,
                    'building_id': None, 'depends_on': ['user_management']},
                   {'feature_key': 'owner_transfers', 'feature_name': 'Owner Transfers',
                    'description': 'Manage unit ownership transfers', 'is_enabled': True, 'category': 'governance',
                    'icon': 'UserPlus', 'routes': ['/admin/owner-transfers'],
                    'created_at': datetime.datetime(2026, 2, 16, 2, 31, 16, 322000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000),
                    'updated_by': 'f26f3caf-710f-4a61-84b1-26d8bcac7042', 'building_id': None,
                    'depends_on': ['user_management']},
                   {'feature_key': 'outstanding_issues_register', 'feature_name': 'Outstanding Issues Register',
                    'description': 'Shared building-wide register for open issues, EC updates, and chair notes',
                    'is_enabled': True, 'category': 'governance', 'icon': 'ClipboardList',
                    'routes': ['/requests/outstanding-issues'],
                    'created_at': datetime.datetime(2026, 4, 12, 22, 46, 34, 840000),
                    'updated_at': datetime.datetime(2026, 4, 12, 22, 46, 34, 840000), 'updated_by': None,
                    'building_id': None, 'depends_on': ['meetings']},
                   {'feature_key': 'owner_units_management', 'feature_name': 'Owners & Units Management',
                    'description': 'Manage owner and unit data', 'is_enabled': True, 'category': 'governance',
                    'icon': 'Building2', 'routes': ['/admin/owners-units'],
                    'created_at': datetime.datetime(2026, 2, 16, 2, 31, 16, 322000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000), 'updated_by': None,
                    'building_id': None, 'depends_on': []},
                   {'feature_key': 'proposals', 'feature_name': 'Proposals & Voting',
                    'description': 'Create and vote on community proposals', 'is_enabled': True,
                    'category': 'governance', 'icon': 'Vote', 'routes': ['/governance/proposals'],
                    'depends_on': ['meetings'], 'building_id': None,
                    'created_at': datetime.datetime(2026, 3, 31, 1, 28, 49, 481000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000), 'updated_by': None},
                   {'feature_key': 'quick_polls', 'feature_name': 'Quick Polls',
                    'description': 'Non-binding micro-governance polls for community voice', 'is_enabled': True,
                    'category': 'governance', 'icon': 'Vote', 'routes': ['/governance/polls'], 'depends_on': [],
                    'building_id': None, 'created_at': datetime.datetime(2026, 4, 1, 0, 5, 3, 926000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000), 'updated_by': None},
                   {'feature_key': 'rental_certificates', 'category': 'governance',
                    'description': 'Request and issue ACT Section 119A Unit Title Rental Certificates (mandatory since Jan 2025)',
                    'feature_name': 'Rental Certificates', 'icon': 'FileText', 'is_enabled': True,
                    'routes': ['/requests/rental-certificates'],
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000),
                    'updated_by': 'f26f3caf-710f-4a61-84b1-26d8bcac7042', 'building_id': None,
                    'depends_on': ['compliance', 'owner_units_management']},
                   {'feature_key': 'strata_roll', 'feature_name': 'Strata Roll',
                    'description': 'Official strata roll / owner register with lot entitlements, unit interests and unit details',
                    'is_enabled': True, 'category': 'governance', 'icon': 'Scroll',
                    'routes': ['/admin/strata-roll'],
                    'created_at': datetime.datetime(2026, 3, 6, 12, 4, 33, 239000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000),
                    'updated_by': 'f26f3caf-710f-4a61-84b1-26d8bcac7042', 'building_id': None,
                    'depends_on': ['owner_units_management']},
                   {'feature_key': 'tenant_approvals', 'feature_name': 'Tenant & Guest Approvals',
                    'description': 'Review and approve tenant and guest registration requests submitted by property owners',
                    'is_enabled': True, 'category': 'governance', 'icon': 'UserCheck',
                    'routes': ['/requests/tenant-approvals'],
                    'created_at': datetime.datetime(2026, 3, 6, 12, 4, 33, 239000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000),
                    'updated_by': 'f26f3caf-710f-4a61-84b1-26d8bcac7042', 'building_id': None,
                    'depends_on': ['user_management']},
                   {'feature_key': 'tenant_renewals', 'feature_name': 'Tenant Renewals',
                    'description': 'Manage tenant lease renewals', 'is_enabled': True, 'category': 'governance',
                    'icon': 'RefreshCw', 'routes': ['/admin/tenant-renewals'],
                    'created_at': datetime.datetime(2026, 2, 16, 2, 31, 16, 322000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000),
                    'updated_by': 'f26f3caf-710f-4a61-84b1-26d8bcac7042', 'building_id': None,
                    'depends_on': ['user_management']},
                   {'feature_key': 'user_feature_permissions', 'feature_name': 'Feature Access Controls',
                    'description': 'Grant or restrict individual user access to specific features independently of their role',
                    'is_enabled': True, 'category': 'governance', 'icon': 'KeyRound',
                    'routes': ['/admin/user-feature-permissions'],
                    'created_at': datetime.datetime(2026, 3, 6, 12, 4, 33, 239000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000), 'updated_by': None,
                    'building_id': None, 'depends_on': ['user_management']},
                   {'feature_key': 'user_management', 'feature_name': 'User Management',
                    'description': 'Create, edit, and manage user accounts', 'is_enabled': True,
                    'category': 'governance', 'icon': 'Users', 'routes': ['/admin/users'],
                    'created_at': datetime.datetime(2026, 2, 16, 2, 31, 16, 322000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000), 'updated_by': None,
                    'building_id': None, 'depends_on': []},
                   {'feature_key': 'user_permissions', 'feature_name': 'Access Control Management',
                    'description': 'Manage granular user permissions and role-based access control settings per role',
                    'is_enabled': True, 'category': 'governance', 'icon': 'Lock',
                    'routes': ['/admin/user-permissions'],
                    'created_at': datetime.datetime(2026, 3, 6, 12, 4, 33, 239000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000), 'updated_by': None,
                    'building_id': None, 'depends_on': ['user_management']},
                   {'feature_key': 'building_risk_index', 'feature_name': 'Global Building Risk Index',
                    'description': 'Composite 0–100 risk score combining asset health, financial stability, reserve adequacy, capital shock risk, and maintenance forecasts. Includes public building report page.',
                    'is_enabled': True, 'category': 'intelligence', 'icon': 'ShieldAlert',
                    'roles': ['super_admin', 'strata_manager', 'chairman', 'strata_admin', 'ec_member', 'owner'],
                    'routes': ['/intelligence/risk-index', '/building/[slug]'],
                    'created_at': datetime.datetime(2026, 3, 17, 11, 55, 25, 518000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000),
                    'updated_by': 'f26f3caf-710f-4a61-84b1-26d8bcac7042', 'building_id': None,
                    'depends_on': ['strata_market_intelligence']},
                   {'feature_key': 'strata_market_intelligence', 'category': 'intelligence',
                    'description': 'ACT-wide suburb strata density heatmap, cluster analysis, TAM calculator, true cost of ownership and financial stress predictor',
                    'feature_name': 'ACT Strata Market Intelligence', 'icon': 'Map', 'is_enabled': True,
                    'roles': ['super_admin', 'strata_manager'], 'routes': ['/intelligence/market'],
                    'building_id': None, 'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000),
                    'updated_by': 'f26f3caf-710f-4a61-84b1-26d8bcac7042', 'depends_on': []},
                   {'feature_key': 'suburb_radar', 'feature_name': 'Suburb Radar',
                    'description': 'Weekly local intelligence digest — property market, ESA incidents, planning',
                    'is_enabled': True, 'category': 'intelligence', 'icon': 'Map',
                    'routes': ['/intelligence/suburb-radar'], 'depends_on': [], 'building_id': None,
                    'created_at': datetime.datetime(2026, 4, 1, 0, 5, 3, 926000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000), 'updated_by': None},
                   {'feature_key': 'owner_hub', 'feature_name': 'OwnerHub — Landlord Platform',
                    'description': 'Self-managed landlord platform: manage investment properties (Eastgate + external), tenancies, rent ledger, inspections and property intelligence in one place.',
                    'is_enabled': True, 'category': 'landlord', 'icon': 'Home',
                    'routes': ['/owner-hub', '/owner-hub/properties',
                               '/owner-hub/tenancies', '/owner-hub/ledger',
                               '/owner-hub/inspections'],
                    'created_at': datetime.datetime(2026, 3, 12, 0, 59, 23, 634000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000), 'updated_by': None,
                    'building_id': None, 'depends_on': []},
                   {'feature_key': 'property_health_score', 'feature_name': 'Property Health Score',
                    'description': 'Weekly property health score (0–100) combining income stability, maintenance backlog, tenant tenure, capital risk and compliance. Gives landlords a single investment quality indicator.',
                    'is_enabled': True, 'category': 'landlord', 'icon': 'Activity',
                    'routes': ['/owner-hub/health-score'],
                    'created_at': datetime.datetime(2026, 3, 12, 0, 59, 23, 634000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000), 'updated_by': None,
                    'building_id': None, 'depends_on': ['owner_hub']},
                   {'feature_key': 'real_estate_agent_portal', 'feature_name': 'Real Estate Agent Portal',
                    'description': 'Dedicated portal for real estate agents to manage assigned properties on behalf of owners: tenant communications, maintenance oversight, lease status, inspection scheduling.',
                    'is_enabled': True, 'category': 'landlord', 'icon': 'Briefcase',
                    'routes': ['/real-estate'],
                    'created_at': datetime.datetime(2026, 3, 12, 0, 59, 23, 634000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000),
                    'updated_by': 'f26f3caf-710f-4a61-84b1-26d8bcac7042', 'building_id': None,
                    'depends_on': ['owner_hub']},
                   {'feature_key': 'tenant_maintenance_portal', 'feature_name': 'Tenant Maintenance Portal',
                    'description': 'RentBetter-inspired tenant maintenance portal: submit requests with photos, track status (Submitted → Assigned → In Progress → Completed), message thread with owner/agent/manager.',
                    'is_enabled': True, 'category': 'landlord', 'icon': 'Wrench',
                    'routes': ['/maintenance/tenant'],
                    'created_at': datetime.datetime(2026, 3, 12, 0, 59, 23, 634000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000), 'updated_by': None,
                    'building_id': None, 'depends_on': ['maintenance', 'owner_hub']},
                   {'feature_key': 'true_cost_ownership', 'feature_name': 'True Cost of Ownership',
                    'description': 'Accurate annual ownership cost calculator including strata levies, maintenance, capital works share, vacancy, financing and 10-year cashflow projection.',
                    'is_enabled': True, 'category': 'landlord', 'icon': 'Calculator',
                    'routes': ['/owner-hub/tco'],
                    'created_at': datetime.datetime(2026, 3, 12, 0, 59, 23, 634000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000), 'updated_by': None,
                    'building_id': None, 'depends_on': ['owner_hub', 'finance']},
                   {'feature_key': 'maintenance_intelligence', 'feature_name': 'Maintenance Intelligence Engine',
                    'description': 'Asset health scoring, predictive maintenance forecasts, 10-year capital works planning and levy stabilization',
                    'is_enabled': True, 'category': 'maintenance', 'icon': 'Brain',
                    'routes': ['/intelligence'],
                    'created_at': datetime.datetime(2026, 3, 6, 12, 51, 3, 896000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000), 'updated_by': None,
                    'building_id': None, 'depends_on': ['asset_register']},
                   {'feature_key': 'request_status_tracking', 'feature_name': 'Request Status Tracking',
                    'description': "Real-time request status timeline for residents — eliminates 'any update?' emails",
                    'is_enabled': True, 'category': 'operations', 'icon': 'ClipboardList',
                    'routes': ['/requests'], 'depends_on': ['smart_requests'], 'building_id': None,
                    'created_at': datetime.datetime(2026, 4, 1, 0, 5, 3, 926000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000), 'updated_by': None},
                   {'feature_key': 'emergency', 'feature_name': 'Emergency Services',
                    'description': 'Quick access to emergency contacts and services', 'is_enabled': True,
                    'category': 'safety', 'icon': 'AlertTriangle', 'routes': ['/emergency'],
                    'created_at': datetime.datetime(2026, 2, 14, 13, 22, 26, 439000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000), 'updated_by': None,
                    'building_id': None, 'depends_on': []},
                   {'feature_key': 'safety_feed', 'feature_name': 'Building Safety Feed',
                    'description': 'Building safety events log for residents and managers', 'is_enabled': True,
                    'category': 'safety', 'icon': 'Shield', 'routes': ['/intelligence/safety-feed'], 'depends_on': [],
                    'building_id': None, 'created_at': datetime.datetime(2026, 4, 1, 0, 5, 3, 926000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000), 'updated_by': None},
                   {'feature_key': 'adaptive_nav', 'feature_name': 'Adaptive Navigation AI', 'category': 'system',
                    'is_enabled': True, 'description': 'Reorders advanced menu items based on user behaviour',
                    'created_at': '2026-04-01T05:45:53.074005+00:00', 'updated_at': '2026-04-01T05:45:53.074005+00:00',
                    'is_test_data': False}, {'feature_key': 'admin_console', 'feature_name': 'Legal & Privacy Console',
                                             'description': 'Manage legal documents, terms of use, privacy policies and compliance records',
                                             'is_enabled': True, 'category': 'system', 'icon': 'ScrollText',
                                             'routes': ['/admin/console'],
                                             'created_at': datetime.datetime(2026, 3, 6, 12, 4, 33, 239000),
                                             'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000),
                                             'updated_by': None, 'building_id': None, 'depends_on': []},
                   {'feature_key': 'asset_register', 'feature_name': 'Asset Register',
                    'description': 'Manage building assets, equipment and infrastructure inventory with lifecycle tracking',
                    'is_enabled': True, 'category': 'system', 'icon': 'Database', 'routes': ['/admin/assets'],
                    'created_at': datetime.datetime(2026, 3, 6, 12, 4, 33, 239000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000), 'updated_by': None,
                    'building_id': None, 'depends_on': ['maintenance']},
                   {'feature_key': 'audit_logs', 'feature_name': 'Audit Logs',
                    'description': 'View system activity and audit logs', 'is_enabled': True, 'category': 'system',
                    'icon': 'History', 'routes': ['/admin/audit-logs'],
                    'created_at': datetime.datetime(2026, 2, 16, 2, 31, 16, 322000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000), 'updated_by': None,
                    'building_id': None, 'depends_on': []},
                   {'feature_key': 'building_onboarding', 'feature_name': 'Building Onboarding Workflow',
                    'description': 'Structured onboarding checklist for new buildings', 'is_enabled': True,
                    'category': 'system', 'icon': 'ClipboardCheck',
                    'routes': ['/admin/portfolio/onboard', '/admin/buildings/onboard'],
                    'depends_on': [], 'building_id': None, 'created_at': datetime.datetime(2026, 4, 1, 0, 5, 3, 926000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000), 'updated_by': None},
                   {'feature_key': 'digital_twin', 'feature_name': 'Digital Twin Architecture',
                    'description': 'Building asset graph — zones, facilities, components and benefit groups for cost allocation',
                    'is_enabled': True, 'category': 'system', 'icon': 'Building2',
                    'routes': ['/settings/digital-twin'],
                    'created_at': datetime.datetime(2026, 3, 6, 12, 51, 3, 896000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000), 'updated_by': None,
                    'building_id': None, 'depends_on': ['asset_register']},
                   {'feature_key': 'email_settings', 'feature_name': 'Email System Configuration',
                    'description': 'Configure SMTP settings, email templates, sender details and delivery preferences',
                    'is_enabled': True, 'category': 'system', 'icon': 'MailCheck',
                    'routes': ['/admin/communications'],
                    'created_at': datetime.datetime(2026, 3, 6, 12, 4, 33, 239000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000), 'updated_by': None,
                    'building_id': None, 'depends_on': []},
                   {'feature_key': 'external_api', 'feature_name': 'External API',
                    'description': 'Enable API key access for external integrations', 'is_enabled': True,
                    'category': 'system', 'icon': 'Shield', 'routes': [],
                    'created_at': datetime.datetime(2026, 3, 9, 3, 13, 32, 775000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000), 'updated_by': None,
                    'building_id': None, 'depends_on': []},
                   {'feature_key': 'impersonation', 'feature_name': 'User Impersonation',
                    'description': 'Allow Super Admins to view the portal as another user for troubleshooting',
                    'is_enabled': True, 'category': 'system', 'icon': 'Users', 'routes': [],
                    'created_at': datetime.datetime(2026, 3, 2, 0, 46, 36, 100000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000), 'building_id': None,
                    'depends_on': []},
                   {'feature_key': 'manage_mail_passwords', 'feature_name': 'Mail Credential Manager',
                    'description': 'Manage @eastgateresidences.com.au email credentials and portal access for residents',
                    'is_enabled': True, 'category': 'system', 'icon': 'KeySquare',
                    'routes': ['/admin/communications'],
                    'created_at': datetime.datetime(2026, 3, 6, 12, 4, 33, 239000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000), 'updated_by': None,
                    'building_id': None, 'depends_on': ['email']},
                   {'feature_key': 'nav_customisation', 'feature_name': 'Navigation Customisation',
                    'category': 'system', 'is_enabled': True,
                    'description': 'Allow users to pin, hide, and reorder nav items',
                    'created_at': '2026-04-01T05:45:53.074005+00:00', 'updated_at': '2026-04-01T05:45:53.074005+00:00',
                    'is_test_data': False},
                   {'feature_key': 'nav_discovery_nudges', 'feature_name': 'Feature Discovery Nudges',
                    'category': 'system', 'is_enabled': True,
                    'description': 'Periodic prompts to explore unused features',
                    'created_at': '2026-04-01T05:45:53.074005+00:00', 'updated_at': '2026-04-01T05:45:53.074005+00:00',
                    'is_test_data': False},
                   {'feature_key': 'notification_cleanup', 'feature_name': 'Notification Cleanup',
                    'description': 'Automatically delete old notifications after a set period (configurable in days)',
                    'is_enabled': True, 'category': 'system', 'icon': 'Trash2', 'routes': [],
                    'created_at': datetime.datetime(2026, 2, 16, 2, 31, 16, 322000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000), 'updated_by': None,
                    'building_id': None, 'depends_on': []},
                   {'feature_key': 'portfolio_dashboard', 'feature_name': 'Portfolio Dashboard',
                    'description': 'Multi-building command centre for strata managers', 'is_enabled': True,
                    'category': 'system', 'icon': 'Building2', 'routes': ['/admin'], 'depends_on': [],
                    'roles': ['super_admin', 'strata_manager'], 'building_id': None,
                    'created_at': datetime.datetime(2026, 4, 1, 0, 5, 3, 926000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000), 'updated_by': None},
                   {'feature_key': 'progressive_nav', 'feature_name': 'Progressive Navigation System',
                    'category': 'system', 'is_enabled': True,
                    'description': 'Three-layer progressive navigation with simple/advanced modes',
                    'created_at': '2026-04-01T05:45:53.074005+00:00', 'updated_at': '2026-04-01T05:45:53.074005+00:00',
                    'is_test_data': False}, {'feature_key': 'rate_limiting', 'feature_name': 'Rate Limiting',
                                             'description': 'Enable IP-based rate limiting for sensitive authentication endpoints',
                                             'is_enabled': True, 'category': 'system', 'icon': 'Gauge', 'routes': [],
                                             'created_at': datetime.datetime(2026, 3, 12, 0, 59, 23, 634000),
                                             'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000),
                                             'updated_by': None, 'building_id': None, 'depends_on': []},
                   {'feature_key': 'scraper_settings', 'feature_name': 'Scraper Settings',
                    'description': 'Configure and manage data scrapers, cron schedules, API usage and thresholds (Super Admin only)',
                    'is_enabled': True, 'category': 'system', 'icon': 'Bot',
                    'routes': ['/admin/scraper-settings'],
                    'created_at': datetime.datetime(2026, 3, 6, 12, 4, 33, 239000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000),
                    'updated_by': 'f26f3caf-710f-4a61-84b1-26d8bcac7042', 'building_id': None, 'depends_on': []},
                   {'feature_key': 'security_ip_logs', 'feature_name': 'Security & IP Protection Logs',
                    'description': 'Monitor IP-based access logs, blocked addresses, rate-limit events and security alerts',
                    'is_enabled': True, 'category': 'system', 'icon': 'ShieldAlert',
                    'routes': ['/admin/security-ip-logs'],
                    'created_at': datetime.datetime(2026, 3, 6, 12, 4, 33, 239000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000), 'updated_by': None,
                    'building_id': None, 'depends_on': []},
                   {'feature_key': 'site_settings', 'feature_name': 'Site Configuration Settings',
                    'description': 'System-wide settings including registration, branding, levy periods and general configuration',
                    'is_enabled': True, 'category': 'system', 'icon': 'Settings', 'routes': ['/settings'],
                    'created_at': datetime.datetime(2026, 3, 6, 12, 4, 33, 239000),
                    'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000), 'updated_by': None,
                    'building_id': None, 'depends_on': []},
                    {'feature_key': 'workflow_governance', 'feature_name': 'Workflow Governance Dashboard',
                     'description': 'Named, observable automations dashboard — shows all workflow runs, health status, and coverage',
                     'is_enabled': True, 'category': 'system', 'icon': 'GitBranch',
                     'routes': ['/admin/workflows'], 'depends_on': [],
                     'roles': ['super_admin', 'strata_manager'], 'building_id': None,
                     'created_at': datetime.datetime(2026, 4, 1, 0, 5, 3, 926000),
                     'updated_at': datetime.datetime(2026, 4, 1, 5, 45, 48, 513000), 'updated_by': None},
                    {'feature_key': 'ops_case_management_pg_enabled', 'feature_name': 'Ops Case Management PG',
                     'description': 'Enable the PostgreSQL-backed unified case/task foundation for the strata-manager operating system.',
                     'is_enabled': False, 'category': 'operations', 'icon': 'Briefcase',
                     'routes': ['/requests/ops/cases'], 'depends_on': [], 'roles': ['super_admin'],
                     'building_id': None, 'created_at': '2026-05-18T00:00:00+00:00',
                     'updated_at': '2026-05-18T00:00:00+00:00', 'updated_by': None},
                    {'feature_key': 'communications_campaigns_pg_enabled', 'feature_name': 'Communications Campaigns PG',
                     'description': 'Enable PostgreSQL-backed newsletters, campaigns, acknowledgements, and campaign drafting workflows.',
                     'is_enabled': False, 'category': 'communications', 'icon': 'Megaphone',
                     'routes': ['/admin/communications'], 'depends_on': [], 'roles': ['super_admin'],
                     'building_id': None, 'created_at': '2026-05-18T00:00:00+00:00',
                     'updated_at': '2026-05-18T00:00:00+00:00', 'updated_by': None},
                    {'feature_key': 'access_device_lifecycle_pg_enabled', 'feature_name': 'Access Device Lifecycle PG',
                     'description': 'Enable PostgreSQL-backed access device request, issuance, return, and deactivation workflows.',
                     'is_enabled': False, 'category': 'operations', 'icon': 'KeyRound',
                     'routes': ['/settings?tab=access-devices', '/requests?tab=access-control'], 'depends_on': [], 'roles': ['super_admin', 'strata_admin', 'strata_manager', 'admin_staff', 'owner', 'tenant', 'real_estate_agent'],
                     'building_id': None, 'created_at': '2026-05-18T00:00:00+00:00',
                     'updated_at': '2026-05-18T00:00:00+00:00', 'updated_by': None},
                    {'feature_key': 'ai_review_panel_enabled', 'feature_name': 'AI Review Panel',
                     'description': 'Expose tenant-scoped AI assessment, recommendation, and human review panel workflows. No automated high-risk actions are enabled by this toggle alone.',
                     'is_enabled': False, 'category': 'ai', 'icon': 'Bot',
                     'routes': ['/admin/ops/review-panel'], 'depends_on': [], 'roles': ['super_admin'],
                     'building_id': None, 'created_at': '2026-05-18T00:00:00+00:00',
                     'updated_at': '2026-05-18T00:00:00+00:00', 'updated_by': None},
                    {'feature_key': 'sustainability_assessments_pg_enabled', 'feature_name': 'Sustainability Assessments PG',
                     'description': 'Enable PostgreSQL-backed sustainability profile, lighting, solar-readiness, and project-benefit foundations.',
                     'is_enabled': False, 'category': 'operations', 'icon': 'Leaf',
                     'routes': ['/intelligence/sustainability'], 'depends_on': [], 'roles': ['super_admin'],
                     'building_id': None, 'created_at': '2026-05-18T00:00:00+00:00',
                     'updated_at': '2026-05-18T00:00:00+00:00', 'updated_by': None}]


async def seed_feature_toggles():
    """Upsert all feature_toggles entries. Safe to re-run."""
    client = AsyncMongoClient(os.environ['MONGO_URL'])
    db = client[os.environ['DB_NAME']]
    upserted = 0
    for entry in FEATURE_TOGGLES:
        result = await db.feature_toggles.update_one(
            {'feature_key': entry['feature_key'], 'building_id': entry.get('building_id')},
            {'$set': entry, '$setOnInsert': {'created_at': entry.get('created_at', entry.get('updated_at', ''))}},
            upsert=True
        )
        if result.upserted_id or result.modified_count:
            upserted += 1
    print(f'feature_toggles: {upserted} upserted ({len(FEATURE_TOGGLES)} total)')
    client.close()


if __name__ == "__main__":
    asyncio.run(seed_feature_toggles())
